Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-06, with the labels that each got.

#1844 chore(release): v1.0.5-beta
  .github/workflows/pr-lint.yml
  CHANGELOG.md
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_price.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/common/Cargo.toml
  mm2src/common/shared_ref_counter/Cargo.toml
  mm2src/common/time_cache.rs
  mm2src/db_common/Cargo.toml
  mm2src/gossipsub/Cargo.toml
  mm2src/hw_common/Cargo.toml
  mm2src/ledger/Cargo.toml
  mm2src/mm2_bin_lib/Cargo.toml
  mm2src/mm2_bitcoin/rpc/Cargo.toml
  mm2src/mm2_bitcoin/script/Cargo.toml
  mm2src/mm2_db/Cargo.toml
  mm2src/mm2_libp2p/Cargo.toml
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch/order_requests_tracker.rs
  mm2src/mm2_metamask/Cargo.toml
  mm2src/mm2_metrics/Cargo.toml
  mm2src/mm2_metrics/src/mm_metrics.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/trezor/Cargo.toml
Labels: under review

#1853 fix(security): improvements
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/hd_wallet_storage/sqlite_storage.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lightning/ln_sql.rs
  mm2src/coins/tx_history_storage/sql_tx_history_storage_v2.rs
  mm2src/coins/utxo/utxo_block_header_storage/sql_block_header_storage.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/common/Cargo.toml
  mm2src/db_common/Cargo.toml
  mm2src/db_common/src/sql_create.rs
  mm2src/db_common/src/sql_delete.rs
  mm2src/db_common/src/sql_insert.rs
  mm2src/db_common/src/sql_query.rs
  mm2src/db_common/src/sql_update.rs
  mm2src/db_common/src/sqlite.rs
  mm2src/gossipsub/Cargo.toml
  mm2src/mm2_libp2p/Cargo.toml
  mm2src/mm2_libp2p/src/atomicdex_behaviour.rs
  mm2src/mm2_libp2p/src/lib.rs
  mm2src/mm2_libp2p/src/peers_exchange.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/database.rs
  mm2src/mm2_main/src/database/my_orders.rs
  mm2src/mm2_main/src/database/my_swaps.rs
  mm2src/mm2_main/src/database/stats_nodes.rs
  mm2src/mm2_main/src/database/stats_swaps.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/best_orders.rs
  mm2src/mm2_main/src/lp_ordermatch/new_protocol.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_metrics/Cargo.toml
  mm2src/mm2_metrics/src/recorder.rs
  mm2src/mm2_net/Cargo.toml
Labels: under review, bug fixing week 2

#1805 feat(zcoin): allow ARRR/ZCOIN compilation in wasm
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_coins.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage.rs
  mm2src/coins/z_coin/storage/blockdb/block_idb.rs
  mm2src/coins/z_coin/storage/blockdb/mod.rs
  mm2src/coins/z_coin/storage/walletdb/mod.rs
  mm2src/coins/z_coin/storage/walletdb/wallet_idb.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_htlc.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
Labels: under review, 1.0.6-beta

#1851 fix(orderbook): age field is set in proper way
  mm2src/mm2_main/src/lp_ordermatch.rs
Labels: bug, under review, bug fixing week 2

#1862 fix(incompatible-dep): rollback rmp
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/mm2_libp2p/Cargo.toml
  mm2src/mm2_main/Cargo.toml
Labels: 1.0.6-beta

#1846 feat(watchtower): move watchtower tests to new testnet
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review

#1869 fix(endpoints): fix price endpoints in lp_price
  mm2src/coins/lp_price.rs
Labels: under review, 1.0.6-beta

#1833 feat(nft): introduce db cache support (non-wasm target)
  mm2src/coins/eth.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/mod.rs
  mm2src/coins/nft/storage/wasm/nft_idb.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/common/common.rs
  mm2src/db_common/src/sql_query.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
Labels: P1, under review, 1.0.6-beta

#1872 fix(logs): remove config string from deserialization error log
  mm2src/mm2_main/src/mm2.rs
Labels: under review, 1.0.6-beta

#1881 ci(pr-validation): check PR labels
  .github/workflows/pr-lint.yml
Labels: CI, under review, 1.0.6-beta

#1879 refactor(adex-cli): orderbook response processing moved
  mm2src/adex_cli/src/adex_config.rs
  mm2src/adex_cli/src/adex_proc/mod.rs
  mm2src/adex_cli/src/adex_proc/response_handler.rs
  mm2src/adex_cli/src/adex_proc/response_handler/orderbook.rs
  mm2src/adex_cli/src/adex_proc/response_handler/smart_fraction_fmt.rs
Labels: Refactoring, under review, adex-cli, 1.0.6-beta

#1884 chore(release): bump mm2 version to 1.0.6-beta
  Cargo.lock
  mm2src/mm2_bin_lib/Cargo.toml
Labels: under review

#1889 fix(adex-cli): fix bug start without config
  mm2src/adex_cli/src/adex_app.rs
  mm2src/adex_cli/src/adex_config.rs
  mm2src/adex_cli/src/adex_proc/adex_proc_impl.rs
  mm2src/adex_cli/src/adex_proc/command.rs
  mm2src/adex_cli/src/adex_proc/response_handler.rs
  mm2src/adex_cli/src/cli.rs
  mm2src/adex_cli/src/logging.rs
  mm2src/adex_cli/src/main.rs
Labels: bug, P1, under review, 1.0.6-beta
