Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-05, with the labels that each got.

#1762 Enhance enable with tokens methods
  CHANGELOG.md
  mm2src/coins/eth.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/coins/utxo/utxo_tx_history_v2.rs
  mm2src/coins_activation/src/bch_with_tokens_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/platform_coin_with_tokens.rs
  mm2src/coins_activation/src/prelude.rs
  mm2src/coins_activation/src/solana_with_tokens_activation.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/mm2_main/tests/docker_tests/slp_tests.rs
  mm2src/mm2_main/tests/docker_tests/solana_tests.rs
  mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
  mm2src/mm2_main/tests/mm2_tests/tendermint_ibc_asset_tests.rs
  mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: under review

#1775 Add proxy support
  CHANGELOG.md
  mm2src/coins/Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
Labels: under review

#1813 update wasm build archive
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
Labels: 1.0.4-beta

#1763 active/passive modes for parent coins
  CHANGELOG.md
  mm2src/coins/lp_coins.rs
  mm2src/coins/test_coin.rs
  mm2src/coins_activation/src/bch_with_tokens_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/platform_coin_with_tokens.rs
  mm2src/coins_activation/src/solana_with_tokens_activation.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_main/tests/docker_tests/slp_tests.rs
  mm2src/mm2_main/tests/docker_tests/solana_tests.rs
  mm2src/mm2_main/tests/mm2_tests/bch_and_slp_tests.rs
  mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
  mm2src/mm2_main/tests/mm2_tests/lightning_tests.rs
  mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: enhancement, under review, 1.0.4-beta

#1728 detect and resolve chain reorganization
  CHANGELOG.md
  mm2src/coins/for_tests/RICK_HEADERS.json
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/utxo_block_header_storage/mod.rs
  mm2src/coins/utxo/utxo_block_header_storage/sql_block_header_storage.rs
  mm2src/coins/utxo/utxo_block_header_storage/wasm/indexeddb_block_header_storage.rs
  mm2src/coins/utxo/utxo_builder/mod.rs
  mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/mm2_bitcoin/spv_validation/Cargo.toml
  mm2src/mm2_bitcoin/spv_validation/src/helpers_validation.rs
  mm2src/mm2_bitcoin/spv_validation/src/storage.rs
  mm2src/mm2_bitcoin/spv_validation/src/work.rs
Labels: 1.0.4-beta

#1817 Fix nft request for wasm target
  CHANGELOG.md
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_tests.rs
Labels: under review, 1.0.4-beta

#1821 update release compilation profile
  CHANGELOG.md
  Cargo.toml
Labels: micro-opt, under review, 1.0.4-beta

#1822 Revert BCHD testnet url to the previous url in unit tests
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: 1.0.4-beta

#1818 add CI flows for `adex-cli`
  .github/dependabot.yml
  .github/workflows/adex-cli.yml
  .github/workflows/dev-build.yml
  .github/workflows/fmt-and-lint.yml
  .github/workflows/release-build.yml
  .github/workflows/test.yml
  .github/workflows/virustotal_scan.yml
  CHANGELOG.md
  Cargo.toml
  mm2src/adex_cli/Cargo.lock
Labels: CI, under review, 1.0.4-beta

#1824 Hotfix: lightning swaps maker payment instructions
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
Labels: P1, 1.0.4-beta

#1815 Support posv
  CHANGELOG.md
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_builder/utxo_conf_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo_signer/src/sign_common.rs
  mm2src/mm2_bitcoin/chain/src/transaction.rs
  mm2src/mm2_bitcoin/script/src/sign.rs
Labels: 1.0.4-beta

#1827 Minor fixes for upcoming v1.0.4-beta release
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
  mm2src/common/common.rs
Labels: 1.0.4-beta

#1829 Update tbnb testnet for iris swap test
  mm2src/mm2_main/tests/mm2_tests/iris_swap.rs
Labels: under review, 1.0.4-beta

#1828 Move ETH tests to the new testnet
  CHANGELOG.md
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/solana_tests.rs
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, 1.0.4-beta

#1834 update v1.0.4-beta date in CHANGELOG.md
  CHANGELOG.md
Labels: 1.0.4-beta

#1836 exclude `wasm-timer` deprecated dependency
  CHANGELOG.md
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_price.rs
  mm2src/common/Cargo.toml
  mm2src/common/time_cache.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch/order_requests_tracker.rs
  mm2src/mm2_metrics/Cargo.toml
  mm2src/mm2_metrics/src/mm_metrics.rs
Labels: under review, 1.0.5-beta

#1837 upgrade `wasm-bindgen`, `getrandom` and `log`
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/common/Cargo.toml
  mm2src/common/shared_ref_counter/Cargo.toml
  mm2src/db_common/Cargo.toml
  mm2src/gossipsub/Cargo.toml
  mm2src/hw_common/Cargo.toml
  mm2src/ledger/Cargo.toml
  mm2src/mm2_bin_lib/Cargo.toml
  mm2src/mm2_bitcoin/rpc/Cargo.toml
  mm2src/mm2_bitcoin/script/Cargo.toml
  mm2src/mm2_db/Cargo.toml
  mm2src/mm2_libp2p/Cargo.toml
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_metamask/Cargo.toml
  mm2src/mm2_net/Cargo.toml
  mm2src/trezor/Cargo.toml
Labels: under review, 1.0.5-beta

#1841 feat(kmd): reduce KMD AUR from 5% to 0.01% starting at nS7HardforkHeight
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/utxo_tests.rs
Labels: P0, under review

#1845 chore(release): bump mm2 version to 1.0.5-beta and add changelog entries
  CHANGELOG.md
  Cargo.lock
  mm2src/mm2_bin_lib/Cargo.toml
Labels: under review

#1854 fix(nft): hot fix moralis tests
  mm2src/coins/nft/nft_tests.rs
Labels: 1.0.5-beta

#1855 fix(kmd): remove conversions from/to float in AUR calculations
  mm2src/coins/utxo.rs
Labels: 1.0.5-beta
