Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-08, with the labels that each got.

#1925 fix(posv): fix missing n_time in posv transactions
  mm2src/coins/utxo.rs
Labels: under review, 1.0.7-beta

#1929 fix(ibc-test): use latest relayer channel for tendermint test
  mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
Labels: under review

#1910 feat(adex-cli): secure connection provided
  mm2src/adex_cli/Cargo.lock
  mm2src/adex_cli/Cargo.toml
  mm2src/adex_cli/src/transport.rs
  mm2src/mm2_net/src/native_http.rs
Labels: under review, adex-cli

#1928 fix(endpoints): update prices url
  mm2src/coins/lp_price.rs
  mm2src/mm2_main/src/lp_ordermatch/simple_market_maker.rs
Labels: under review, 1.0.7-beta

#1926 fix(nft): add log_index to history table and use in PK
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/db_test_helpers.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/nft_idb.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
Labels: P0, under review, 1.0.7-beta

#1927 feat(trading-proto-upgrade): UTXO PoC + State machine refactor
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/swap_proto_v2_scripts.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tx_history_v2.rs
  mm2src/coins/utxo_signer/src/with_key_pair.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/common/patterns/state_machine.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/mod.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_net/src/wasm_ws.rs
Labels: under review, 1.0.7-beta

#1938 fix(cli): use the updated activation scheme
  mm2src/adex_cli/src/rpc_data.rs
Labels: under review, adex-cli, 1.0.7-beta

#1944 fix(kmd): use kmd rewards for fees if change + interest is below dust
  mm2src/coins/qrc20.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_withdraw.rs
  mm2src/coins/z_coin.rs
Labels: P1, under review, 1.0.7-beta

#1949 chore(contact info update): replace old github username
  docs/GIT_FLOW_AND_WORKING_PROCESS.md
  mm2src/coins/tendermint/iris/htlc.rs
Labels: under review

#1933 fix(hd-wallet): enable/withdraw using any account'/change/address_index
  mm2src/adex_cli/src/scenarios/init_mm2_cfg.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/lightning/ln_events.rs
  mm2src/coins/lightning/ln_utils.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/rpc_command/tendermint/ibc_withdraw.rs
  mm2src/coins/solana.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_withdraw.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage/walletdb/mod.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/crypto/src/crypto_ctx.rs
  mm2src/crypto/src/global_hd_ctx.rs
  mm2src/crypto/src/hw_ctx.rs
  mm2src/crypto/src/lib.rs
  mm2src/crypto/src/standard_hd_path.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/wasm_tests.rs
  mm2src/mm2_main/tests/docker_tests/docker_ordermatch_tests.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/slp_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/docker_tests/swaps_confs_settings_sync_tests.rs
  mm2src/mm2_main/tests/docker_tests/swaps_file_lock_tests.rs
  mm2src/mm2_main/tests/integration_tests_common/mod.rs
  mm2src/mm2_main/tests/mm2_tests/bch_and_slp_tests.rs
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/iris_swap.rs
  mm2src/mm2_main/tests/mm2_tests/lightning_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
  mm2src/mm2_main/tests/mm2_tests/z_coin_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: QA, under review, 1.0.7-beta, docs
