Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-12, with the labels that each got.

#2018 chore(release): bump mm2 version to 2.0.0-beta
  Cargo.lock
  mm2src/mm2_bin_lib/Cargo.toml
Labels: under review, 2.0.0-beta

#2024 chore(network): update seednodes for netid 8762
  mm2src/coins/lp_price.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_ordermatch/simple_market_maker.rs
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/behaviours/mod.rs
  mm2src/mm2_p2p/src/lib.rs
  mm2src/mm2_p2p/src/network.rs
Labels: P1, under review, 2.0.0-beta

#1989 feat(nft): move db lock, add tx fee and confirmations
  Cargo.lock
  mm2src/coins/eth.rs
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/db_test_helpers.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/mod.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/db_common/Cargo.toml
  mm2src/db_common/src/async_conn_tests.rs
  mm2src/db_common/src/async_sql_conn.rs
  mm2src/db_common/src/lib.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: QA, under review, sec-review, docs, no-deps, 2.0.0-beta

#2026 fix(config): accept a string for rpcport value
  mm2src/mm2_core/src/mm_ctx.rs
Labels: under review, 2.0.0-beta

#2030 deps(network): sync with upstream yamux
  Cargo.lock
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/behaviours/peers_exchange.rs
  mm2src/mm2_p2p/src/behaviours/request_response.rs
Labels: enhancement, P1, under review, sec-review, deps-review, 2.0.0-beta

#2032 fix(price_endpoints): add cached url
  mm2src/coins/lp_price.rs
Labels: under review, 2.0.0-beta

#2034 chore(network): write network information to stdout
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/lib.rs
Labels: under review, 2.0.0-beta

#2037 chore(release): add changelog entries for v2.0.0-beta
  CHANGELOG.md
Labels: under review

#2038 fix(p2p): handle encode_and_sign errors
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_p2p/src/lib.rs
Labels: P1, under review, 2.0.0-beta

#1930 feat(tx): add new sign_raw_transaction rpc for UTXO and EVM coins
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lightning/ln_events.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/rpc_command/lightning/open_channel.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_withdraw.rs
  mm2src/coins/utxo_signer/src/with_key_pair.rs
  mm2src/coins/z_coin.rs
  mm2src/mm2_bitcoin/keys/src/address.rs
  mm2src/mm2_bitcoin/keys/src/private.rs
  mm2src/mm2_bitcoin/script/src/builder.rs
  mm2src/mm2_bitcoin/script/src/script.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, 2.1.0-beta

#2013 feat(UTXO): balance event streaming for Electrum clients
  mm2src/coins/coin_balance.rs
  mm2src/coins/rpc_command/get_new_address.rs
  mm2src/coins/rpc_command/hd_account_balance_rpc_error.rs
  mm2src/coins/rpc_command/init_scan_for_new_addresses.rs
  mm2src/coins/tendermint/tendermint_balance_events.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/utxo_balance_events.rs
  mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_wasm_tests.rs
Labels: enhancement, QA, under review, 2.1.0-beta, sec-review, no-deps

#2015 feat(trading-proto-upgrade): wasm DB, kickstart, refund states, v2 RPCs
  .gitignore
  mm2src/coins/lp_coins.rs
  mm2src/common/bool_as_int.rs
  mm2src/common/common.rs
  mm2src/crypto/src/privkey.rs
  mm2src/mm2_db/src/indexed_db/drivers/upgrader.rs
  mm2src/mm2_main/src/database.rs
  mm2src/mm2_main/src/database/my_swaps.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/my_swaps_storage.rs
  mm2src/mm2_main/src/lp_swap/saved_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_v2_common.rs
  mm2src/mm2_main/src/lp_swap/swap_v2_rpcs.rs
  mm2src/mm2_main/src/lp_swap/swap_wasm_db.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/src/wasm_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_state_machine/src/state_machine.rs
  mm2src/mm2_state_machine/src/storable_state_machine.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: QA, under review, 2.1.0-beta, sec-review, no-deps

#2040 chore(config): remove vscode launchjson
  .gitignore
  .vscode/launch.json
Labels: under review, 2.1.0-beta

#1996 feat(zcoin): implement zcoin/pirate transport layer for WASM
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/lp_price.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/tendermint/rpc/tendermint_wasm_rpc.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage/blockdb/blockdb_idb_storage.rs
  mm2src/coins/z_coin/storage/blockdb/mod.rs
  mm2src/coins/z_coin/storage/walletdb/wallet_sql_storage.rs
  mm2src/coins/z_coin/storage/walletdb/wasm/storage.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_params/indexeddb.rs
  mm2src/coins/z_coin/z_params/mod.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/coins_activation/src/context.rs
  mm2src/coins_activation/src/lib.rs
  mm2src/coins_activation/src/prelude.rs
  mm2src/common/common.rs
  mm2src/crypto/src/hw_rpc_task.rs
  mm2src/mm2_db/src/indexed_db/indexed_db.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/src/wasm_tests.rs
  mm2src/mm2_main/tests/integration_tests_common/mod.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_main/tests/mm2_tests/z_coin_tests.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/grpc_web.rs
  mm2src/mm2_net/src/lib.rs
  mm2src/mm2_net/src/transport.rs
  mm2src/mm2_net/src/wasm/body_stream.rs
  mm2src/mm2_net/src/wasm/http.rs
  mm2src/mm2_net/src/wasm/mod.rs
  mm2src/mm2_net/src/wasm/tonic_client.rs
  mm2src/mm2_net/src/wasm/wasm_ws.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review
