Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-07, with the labels that each got.

#1894 feat(cosmos): dynamic gas price and gas limit
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/tendermint/ibc_withdraw.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
Labels: under review

#1856 fix(adex-cli): the posibility to start mm2 under regular user was pro…
  mm2src/adex_cli/src/scenarios/mm2_proc_mng.rs
Labels: under review, 1.0.6-beta

#1897 fix(watchtower): disable watchers
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: bug, P0, under review, 1.0.6-beta

#1877 feat(nft): db implementation (wasm target)
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/db_test_helpers.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/mod.rs
  mm2src/coins/nft/storage/wasm/nft_idb.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/common/common.rs
Labels: P1, under review, 1.0.6-beta

#1903 feat(repo): renaming kick-off
  .github/workflows/adex-cli.yml
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  README.md
  docs/CONTRIBUTING.md
  docs/DEV_ENVIRONMENT.md
  docs/PR_REVIEW_CHECKLIST.md
Labels: under review

#1899 feat(ci): check if version was bumped
  .github/workflows/validate-mm2-version.yml
  scripts/ci/validate-version-bump.py
Labels: CI, under review

#1907 test(new-flag): run all tests ignoring the failed ones
  .github/workflows/adex-cli.yml
  .github/workflows/test.yml
Labels: under review

#1914 fix(nft): fix notes for 1.0.6-beta
  mm2src/coins/eth.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/db_test_helpers.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/mm2_core/src/mm_ctx.rs
Labels: P1, under review, 1.0.6-beta

#1915 fix(utxo): avoid index out of bounds panics in tx_details_by_hash
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common/utxo_tx_history_v2_common.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
Labels: under review

#1920 fix(adex-cli): remove activation scheme before testing
  mm2src/adex_cli/src/activation_scheme_db/init_activation_scheme.rs
  mm2src/adex_cli/src/activation_scheme_db/mod.rs
  mm2src/adex_cli/src/adex_config.rs
  mm2src/adex_cli/src/tests/mod.rs
Labels: under review

#1913 feat(adex-cli): introduce unix-mode
  mm2src/adex_cli/src/adex_config.rs
  mm2src/adex_cli/src/helpers.rs
Labels: under review, adex-cli, 1.0.7-beta

#1912 feat(adex-cli): provide activation request types to prevent malicious…
  mm2src/adex_cli/src/activation_scheme_db/activation_scheme_impl.rs
  mm2src/adex_cli/src/adex_proc/adex_proc_impl.rs
  mm2src/adex_cli/src/main.rs
  mm2src/adex_cli/src/rpc_data.rs
  mm2src/adex_cli/src/tests/mod.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/mm2_rpc/src/data/legacy.rs
  mm2src/mm2_rpc/src/data/legacy/activation.rs
  mm2src/mm2_rpc/src/data/legacy/activation/eth.rs
  mm2src/mm2_rpc/src/data/legacy/activation/utxo.rs
  mm2src/mm2_rpc/src/data/legacy/orders.rs
  mm2src/mm2_rpc/src/data/legacy/utility.rs
  mm2src/mm2_rpc/src/data/legacy/wallet.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, adex-cli
