Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-10, with the labels that each got.

#1971 fix(fee): remove fixed 0.0001 min threshold for TakerFee
  mm2src/coins/eth.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: under review, breaking-change, 1.1.0-beta

#1981 fix(tests): p2p ctx mocking issue
  Cargo.lock
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/p2p.rs
Labels: bug, under review, 1.1.0-beta

#1988 refactor(chore): improved deduplications
  mm2src/coins/lp_coins.rs
  mm2src/mm2_err_handle/src/mm_error.rs
Labels: micro-opt, under review, 1.1.0-beta

#1990 fix(tests): fix unstable tbch tests and failing price threshold test
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
Labels: under review

#1991 fix(transactions): add cryptocondition script type
  mm2src/mm2_bitcoin/rpc/src/v1/types/script.rs
  mm2src/mm2_bitcoin/script/src/script.rs
Labels: under review

#1992 fix(tests): refactor tbch electrums list and remove non working ones
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/mm2_main/tests/mm2_tests/bch_and_slp_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review

#1997 fix(cli): make mm2-libp2p optional in mm2_net for adex-cli
  mm2src/adex_cli/Cargo.lock
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/for_tests/RICK_HEADERS.json
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_wasm_tests.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/wasm_tests.rs
  mm2src/mm2_main/tests/integration_tests_common/mod.rs
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
  mm2src/mm2_main/tests/mm2_tests/z_coin_tests.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/lib.rs
  mm2src/mm2_net/src/wasm_ws.rs
  mm2src/mm2_test_helpers/src/electrums.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, 1.1.0-beta

#1998 fix(web3): try next web3 node on response error
  mm2src/coins/eth/web3_transport/http_transport.rs
Labels: under review, 1.1.0-beta

#1908 fix(watchtower): fix watchtower taker-side restart bug
  mm2src/coins/eth.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/z_coin.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/for_tests/recreate_maker_swap_maker_payment_wait_confirm_failed_taker_saved.json
  mm2src/mm2_main/src/for_tests/recreate_maker_swap_taker_saved.json
  mm2src/mm2_main/src/for_tests/recreate_taker_swap_taker_expected.json
  mm2src/mm2_main/src/for_tests/recreate_taker_swap_taker_payment_wait_confirm_failed_taker_expected.json
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/recreate_swap_data.rs
  mm2src/mm2_main/src/lp_swap/saved_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_restart.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: QA, under review, sec-review, docs, no-deps, 1.1.0-beta

#1978 feat(channels): wasm, coin balance and socket impl
  Cargo.lock
  mm2src/adex_cli/Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/tendermint/mod.rs
  mm2src/coins/tendermint/rpc/tendermint_native_rpc.rs
  mm2src/coins/tendermint/rpc/tendermint_wasm_rpc.rs
  mm2src/coins/tendermint/tendermint_balance_events.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins_activation/Cargo.toml
  mm2src/coins_activation/src/bch_with_tokens_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/platform_coin_with_tokens.rs
  mm2src/coins_activation/src/solana_with_tokens_activation.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/common/common.rs
  mm2src/mm2_event_stream/Cargo.toml
  mm2src/mm2_event_stream/src/behaviour.rs
  mm2src/mm2_event_stream/src/lib.rs
  mm2src/mm2_libp2p/src/atomicdex_behaviour.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/lib.rs
  mm2src/mm2_net/src/network_event.rs
  mm2src/mm2_net/src/wasm_event_stream.rs
Labels: enhancement, under review, sec-review, deps-review, 1.1.0-beta

#1980 feat(trading-proto-upgrade): sql storage wip + protocol enhancement
  mm2src/coins/lp_coins.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/swap_proto_v2_scripts.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/mm2_bitcoin/chain/src/transaction.rs
  mm2src/mm2_main/src/database.rs
  mm2src/mm2_main/src/database/my_swaps.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/komodefi.swap_v2.pb.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/swap_v2.proto
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_number/src/mm_number.rs
  mm2src/mm2_state_machine/src/state_machine.rs
Labels: under review, sec-review, no-deps, 1.1.0-beta
