Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-11, with the labels that each got.

#2001 fix(rpc): add 'version' to `PUBLIC_METHODS`
  mm2src/mm2_main/src/rpc.rs
Labels: under review

#1959 feat(nft): exclude spam and phishing, refactored db
  mm2src/coins/hd_wallet_storage/wasm_storage.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/db_test_helpers.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/nft_idb.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/coins/tx_history_storage/wasm/tx_history_db.rs
  mm2src/coins/utxo/utxo_block_header_storage/wasm/indexeddb_block_header_storage.rs
  mm2src/coins/z_coin/storage/blockdb/block_idb.rs
  mm2src/coins/z_coin/storage/walletdb/wallet_idb.rs
  mm2src/common/common.rs
  mm2src/mm2_db/src/indexed_db/indexed_db.rs
  mm2src/mm2_event_stream/src/controller.rs
  mm2src/mm2_gui_storage/src/account/storage/wasm_storage.rs
  mm2src/mm2_main/src/lp_ordermatch/ordermatch_wasm_db.rs
  mm2src/mm2_main/src/lp_swap/swap_wasm_db.rs
  mm2src/mm2_net/src/native_http.rs
  mm2src/mm2_net/src/transport.rs
  mm2src/mm2_net/src/wasm_http.rs
Labels: QA, under review, docs, 1.1.0-beta

#2002 chore(license): update copyright / license
  LEGAL/CONTRIBUTOR-LICENSE-AGREEMENT
  LEGAL/LICENSE-COPYRIGHT-NOTICE
  examples/README.md
  examples/wasm/README.md
  mm2src/coins/eth.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/utxo.rs
  mm2src/crypto/src/privkey.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
Labels: under review

#2003 chore(containers and docs): update docs and container images
  .docker/Dockerfile
  .docker/Dockerfile.ci-container
  .docker/Dockerfile.ubuntu.ci
  README.md
  docs/RASPBERRY_PI4_CROSS.md
Labels: micro-opt, under review, docs

#2006 feat(UTXO swaps): kmd burn plan impl
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/mm2_bitcoin/script/src/builder.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: enhancement, P1, QA, under review, breaking-change, sec-review, docs, no-deps, 1.1.0-beta
