Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-04, with the labels that each got.

#1747 set default log level
  CHANGELOG.md
  mm2src/mm2_main/src/mm2.rs
Labels: bug, under review

#1729 adex tool was introduced
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  mm2src/adex_cli/Cargo.toml
  mm2src/adex_cli/src/cli.rs
  mm2src/adex_cli/src/log.rs
  mm2src/adex_cli/src/main.rs
  mm2src/adex_cli/src/scenarios/helpers.rs
  mm2src/adex_cli/src/scenarios/init_coins.rs
  mm2src/adex_cli/src/scenarios/init_mm2_cfg.rs
  mm2src/adex_cli/src/scenarios/inquire_extentions.rs
  mm2src/adex_cli/src/scenarios/mm2_proc_mng.rs
  mm2src/adex_cli/src/scenarios/mod.rs
  mm2src/common/Cargo.toml
  mm2src/common/build.rs
  mm2src/common/common.rs
  mm2src/common/password_policy.rs
  mm2src/mm2_main/src/mm2.rs
Labels: under review

#1751 stream stdout/err to a file
  .gitignore
  CHANGELOG.md
  Cargo.lock
  mm2src/common/Cargo.toml
  mm2src/common/common.rs
  mm2src/common/log.rs
  mm2src/common/log/native_log.rs
  mm2src/gossipsub/Cargo.toml
  mm2src/mm2_libp2p/Cargo.toml
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_ordermatch/simple_market_maker_tests.rs
  mm2src/mm2_main/src/mm2.rs
Labels: under review

#1754 remove unnecessary files
  deny.toml
Labels: under review

#1757 avoid waiting for all EVM nodes to sync the latest nonce
  CHANGELOG.md
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: under review

#1759 update compilation profiles
  .docker/Dockerfile.dev-release
  .dockerignore
  .github/workflows/dev-build.yml
  .github/workflows/fmt-and-lint.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Cargo.toml
Labels: under review

#1755 validate p2p messages and topics
  CHANGELOG.md
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/mm2_libp2p/src/lib.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/dummy_files/iris_nimda_history.json
  mm2src/mm2_test_helpers/dummy_files/iris_test_history.json
Labels: under review, bug fixing week 1

#1765 iris ethermint compatibility implementation
  CHANGELOG.md
  mm2src/coins/tendermint/iris/ethermint_account.rs
  mm2src/coins/tendermint/iris/mod.rs
  mm2src/coins/tendermint/tendermint_coin.rs
Labels: enhancement, under review

#1767 fix `get_receiver_trade_fee` for cosmos
  CHANGELOG.md
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/z_coin.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
Labels: bug, under review

#1760 Enable clippy --all-features on CI
  .github/workflows/fmt-and-lint.yml
  CHANGELOG.md
  mm2src/coins/solana.rs
  mm2src/coins/solana/solana_common_tests.rs
  mm2src/coins/solana/solana_tests.rs
  mm2src/coins/solana/spl_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/mod.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/docker_tests/swaps_file_lock_tests.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/mod.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, bug fixing week 1

#1753 use OS generated secrets
  CHANGELOG.md
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/common/common.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: under review, bug fixing week 1
