Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2023-09, with the labels that each got.

#1955 fix(tests): ignore failing tests due to BCHD
  mm2src/coins/utxo/bchd_grpc.rs
  mm2src/coins/utxo/slp.rs
Labels: under review

#1954 chore(mm2 binary): remove debug info from release binary
  Cargo.toml
Labels: under review

#1922 feat(zcoin): allow ARRR to sync using a start date
  .github/workflows/test.yml
  mm2src/coins/utxo/utxo_builder/mod.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage/blockdb/mod.rs
  mm2src/coins/z_coin/storage/walletdb/mod.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/coins_activation/src/z_coin_activation.rs
  mm2src/mm2_main/tests/integration_tests_common/mod.rs
  mm2src/mm2_main/tests/mm2_tests/mod.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_main/tests/mm2_tests/z_coin_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: P1, QA, under review, 1.0.7-beta, sec-review, docs, no-deps

#1961 chore(release): add changelog entries for v1.0.7-beta
  CHANGELOG.md
Labels: under review

#1931 fix(tests): fix regex parsing passphrase from .env file
  docs/DEV_ENVIRONMENT.md
  mm2src/coins/eth/eth_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, 1.1.0-beta

#1965 chore(docs): run WASM tests with Cargo
  docs/DEV_ENVIRONMENT.md
Labels: under review

#1967 fix(zcoin): resume previous sync if sync_params are not provided
  mm2src/coins/z_coin/storage/walletdb/mod.rs
  mm2src/coins/z_coin/z_rpc.rs
Labels: QA, under review, docs, 1.1.0-beta

#1969 chore(release): bump mm2 version to 1.1.0-beta
  Cargo.lock
  mm2src/mm2_bin_lib/Cargo.toml
Labels: under review

#1970 fix(tests): fix failing tests due to RICK/MORTY
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/mm2_test_helpers/src/electrums.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review

#1958 feat(trading-proto-upgrade): swap UTXO PoC using Storable State Machine.
  Cargo.lock
  Cargo.toml
  mm2src/coins/Cargo.toml
  mm2src/coins/coin_errors.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/swap_proto_v2_scripts.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tx_history_v2.rs
  mm2src/coins/utxo_signer/src/with_key_pair.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/common/common.rs
  mm2src/mm2_bitcoin/script/src/sign.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/build.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/check_balance.rs
  mm2src/mm2_main/src/lp_swap/komodefi.swap_v2.pb.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/swap_v2.proto
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/wasm_ws.rs
  mm2src/mm2_state_machine/Cargo.toml
  mm2src/mm2_state_machine/src/lib.rs
  mm2src/mm2_state_machine/src/prelude.rs
  mm2src/mm2_state_machine/src/state_machine.rs
  mm2src/mm2_state_machine/src/storable_state_machine.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: QA, under review, sec-review, no-deps, 1.1.0-beta

#1945 feat(event streaming): implement push-only streaming channels and SSE
  Cargo.lock
  Cargo.toml
  examples/sse/README.md
  examples/sse/index.html
  examples/wasm/README.md
  examples/wasm/index.html
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_event_stream/Cargo.toml
  mm2src/mm2_event_stream/src/behaviour.rs
  mm2src/mm2_event_stream/src/controller.rs
  mm2src/mm2_event_stream/src/lib.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/lib.rs
  mm2src/mm2_net/src/network_event.rs
  mm2src/mm2_net/src/p2p.rs
  mm2src/mm2_net/src/sse_handler.rs
Labels: enhancement, QA, under review, sec-review, docs, no-deps, 1.1.0-beta
