Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-05, with the labels that each got.

#2102 feat(app-dir): implement root application dir `.kdf`
  mm2src/common/common.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/mm2.rs
Labels: enhancement, under review

#2098 refactor(memory): memory usage improvements
  mm2src/adex_cli/src/scenarios/mm2_proc_mng.rs
  mm2src/coins/eth.rs
  mm2src/coins/lightning/ln_p2p.rs
  mm2src/coins/lightning/ln_sql.rs
  mm2src/coins/lightning/ln_utils.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo_signer/src/with_key_pair.rs
  mm2src/coins/z_coin/storage/walletdb/wasm/storage.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/coins/z_coin/z_tx_history.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/slp_token_activation.rs
  mm2src/coins_activation/src/spl_token_activation.rs
  mm2src/coins_activation/src/tendermint_token_activation.rs
  mm2src/common/shared_ref_counter/src/enable.rs
  mm2src/mm2_bitcoin/keys/src/cashaddress.rs
  mm2src/mm2_bitcoin/spv_validation/src/lib.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/orderbook_rpc.rs
  mm2src/mm2_main/src/lp_stats.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_metrics/src/mm_metrics.rs
  mm2src/trezor/src/transport/udp.rs
Labels: Refactoring, micro-opt, under review

#2114 fix(utxo-swap): apply events occurred while taker down
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_restart.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: under review

#2115 fix(eth): remove my_address from sign_and_send_transaction_with_keypair
  mm2src/coins/eth.rs
Labels: under review

#2116 fix(tests): set txfee for some tbtc tests
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review

#2088 feat(tendermint): pubkey-only activation and unsigned tx
  Cargo.lock
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/eth_withdraw.rs
  mm2src/coins/hd_wallet/errors.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/history.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/rpc_command/tendermint/ibc_transfer_channels.rs
  mm2src/coins/rpc_command/tendermint/ibc_withdraw.rs
  mm2src/coins/rpc_command/tendermint/mod.rs
  mm2src/coins/sia.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/solana_decode_tx_helpers.rs
  mm2src/coins/solana/solana_tests.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/solana/spl_tests.rs
  mm2src/coins/tendermint/ibc/transfer_v1.rs
  mm2src/coins/tendermint/mod.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/tx_history_storage/sql_tx_history_storage_v2.rs
  mm2src/coins/tx_history_storage/tx_history_v2_tests.rs
  mm2src/coins/tx_history_storage/wasm/tx_history_storage_v2.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_tx_history_v2.rs
  mm2src/coins/utxo/utxo_withdraw.rs
  mm2src/coins/z_coin.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/common/common.rs
  mm2src/common/expirable_map.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/data_asker.rs
  mm2src/mm2_core/src/lib.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_event_stream/src/lib.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: enhancement, under review

#2118 fix(swap): use tmp file for swap and order files
  mm2src/mm2_main/src/lp_ordermatch/my_orders_storage.rs
  mm2src/mm2_main/src/lp_swap/saved_swap.rs
Labels: under review

#2053 fix(p2pk): show P2PK balance
  mm2src/coins/lightning/ln_events.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bchd_grpc.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_withdraw.rs
  mm2src/coins/utxo_signer/src/lib.rs
  mm2src/coins/utxo_signer/src/sign_params.rs
  mm2src/coins/utxo_signer/src/with_key_pair.rs
  mm2src/coins/z_coin/z_htlc.rs
  mm2src/crypto/src/privkey.rs
  mm2src/mm2_bitcoin/keys/src/address.rs
  mm2src/mm2_bitcoin/keys/src/address/address_builder.rs
  mm2src/mm2_bitcoin/keys/src/lib.rs
  mm2src/mm2_bitcoin/keys/src/public.rs
  mm2src/mm2_bitcoin/script/src/sign.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: under review

#2119 fix(p2pk-tests): fix p2pk tests post merge
  mm2src/coins/rpc_command/tendermint/ibc_transfer_channels.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tx_history_storage/sql_tx_history_storage_v2.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_tx_history_v2.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: under review

#2125 fix(test): improve log wait condition to fix taker restart test
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: under review

#2123 fix(core): improve validation rules for table names
  mm2src/coins/lightning/ln_sql.rs
  mm2src/coins/lightning/ln_utils.rs
  mm2src/db_common/src/sqlite.rs
Labels: enhancement, P1, under review

#2130 fix(core): tendermint withdraws on hd accounts
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
Labels: bug, P0, under review
