Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-04, with the labels that each got.

#2090 fix(eth): error handling in RPCs
  mm2src/coins/eth/eth_rpc.rs
Labels: under review, 2.1.0-beta

#2014 feat(crypto): mnemonic generation/encryption/decryption/storage
  Cargo.lock
  mm2src/adex_cli/Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/solana/solana_common_tests.rs
  mm2src/coins/solana/solana_tests.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/common/Cargo.toml
  mm2src/crypto/Cargo.toml
  mm2src/crypto/src/decrypt.rs
  mm2src/crypto/src/encrypt.rs
  mm2src/crypto/src/global_hd_ctx.rs
  mm2src/crypto/src/key_derivation.rs
  mm2src/crypto/src/lib.rs
  mm2src/crypto/src/mnemonic.rs
  mm2src/crypto/src/privkey.rs
  mm2src/crypto/src/slip21.rs
  mm2src/gossipsub/Cargo.toml
  mm2src/mm2_bitcoin/crypto/Cargo.toml
  mm2src/mm2_bitcoin/crypto/src/lib.rs
  mm2src/mm2_bitcoin/spv_validation/Cargo.toml
  mm2src/mm2_bitcoin/spv_validation/src/helpers_validation.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_db/src/indexed_db/db_lock.rs
  mm2src/mm2_db/src/indexed_db/indexed_db.rs
  mm2src/mm2_libp2p/Cargo.toml
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_wallet.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_storage.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_wasm_db.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_metrics/Cargo.toml
  mm2src/mm2_metrics/src/mm_metrics.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/lib.rs
Labels: QA, under review, 2.1.0-beta, sec-review, docs, deps-review

#2089 fix(zcoin): syncing and activation improvements
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/coins_activation/src/z_coin_activation.rs
Labels: under review, 2.1.0-beta, sec-review, no-deps

#2095 deps(zcoin): use librustzcash that uses the same `aes` version as mm2
  Cargo.lock
  mm2src/coins/Cargo.toml
Labels: under review

#2096 fix(wasm): websocket url validation
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/wasm/wasm_ws.rs
Labels: under review, 2.1.0-beta

#2079 feat(coin): support nucleus as an alternative to iris HTLC
  mm2src/coins/lp_coins.rs
  mm2src/coins/tendermint/ethermint_account.rs
  mm2src/coins/tendermint/htlc/iris/htlc.rs
  mm2src/coins/tendermint/htlc/iris/htlc_proto.rs
  mm2src/coins/tendermint/htlc/iris/mod.rs
  mm2src/coins/tendermint/htlc/mod.rs
  mm2src/coins/tendermint/htlc/nucleus/htlc.rs
  mm2src/coins/tendermint/htlc/nucleus/htlc_proto.rs
  mm2src/coins/tendermint/htlc/nucleus/mod.rs
  mm2src/coins/tendermint/ibc/mod.rs
  mm2src/coins/tendermint/ibc/transfer_v1.rs
  mm2src/coins/tendermint/iris/htlc.rs
  mm2src/coins/tendermint/iris/mod.rs
  mm2src/coins/tendermint/mod.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/mm2_main/tests/mm2_tests/tendermint_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: enhancement, under review

#2101 fix(eth_tests): remove ETH_DEV_NODE from tests
  .github/workflows/dev-build.yml
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/eth/web3_transport/mod.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/eth_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review

#2099 fix(BCH): deserialize BCH header that uses KAWPOW version correctly
  mm2src/coins/utxo/bch.rs
  mm2src/mm2_bitcoin/chain/src/block_header.rs
  mm2src/mm2_bitcoin/serialization/src/reader.rs
Labels: under review

#2086 feat(sia): initial Sia integration
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_coins.rs
  mm2src/coins/sia.rs
  mm2src/coins/sia/address.rs
  mm2src/coins/sia/blake2b_internal.rs
  mm2src/coins/sia/encoding.rs
  mm2src/coins/sia/http_client.rs
  mm2src/coins/sia/spend_policy.rs
  mm2src/coins_activation/Cargo.toml
  mm2src/coins_activation/src/context.rs
  mm2src/coins_activation/src/lib.rs
  mm2src/coins_activation/src/prelude.rs
  mm2src/coins_activation/src/sia_coin_activation.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
Labels: in progress

#2103 fix(sia): fix sia compilation after hd wallet PR merge
  mm2src/coins/sia.rs
  mm2src/coins_activation/src/sia_coin_activation.rs
Labels: under review

#2097 docs(README): remove outdated information
  README.md
Labels: documentation, under review

#2106 fix(tendermint): fee calculation
  mm2src/coins/tendermint/tendermint_token.rs
Labels: bug, High priority, under review
