Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-11, with the labels that each got.

#2249 fix(legacy-swap): remove the need for takers to confirm their payment
  mm2src/coins/qrc20/swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: under review

#2242 fix(legacy-swap): check for confirmations on recover taker
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
Labels: under review

#2262 fix(tests): add more sepolia endpoints in tests
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review

#2259 fix(hd-wallet): use `CoinBalanceMap` for UTXO and QTUM
  mm2src/coins/rpc_command/account_balance.rs
  mm2src/coins/rpc_command/get_new_address.rs
  mm2src/coins/rpc_command/init_account_balance.rs
  mm2src/coins/rpc_command/init_create_account.rs
  mm2src/coins/rpc_command/init_scan_for_new_addresses.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins_activation/src/utxo_activation/common_impl.rs
  mm2src/coins_activation/src/utxo_activation/utxo_standard_activation_result.rs
  mm2src/mm2_main/tests/integration_tests_common/mod.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: under review, docs, breaking-change: API

#2209 fix(nft): add token_id field to the tx history primary key, fix balance
  mm2src/coins/eth.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/db_test_helpers.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/nft_idb.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/coins/z_coin/storage/walletdb/wasm/storage.rs
  mm2src/mm2_db/src/indexed_db/drivers/upgrader.rs
  mm2src/mm2_main/src/lp_swap/saved_swap.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_number/src/lib.rs
Labels: under review

#2265 refactor(MarketCoinOps): make `wait_for_htlc_tx_spend` async
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lightning/ln_platform.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/siacoin.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
Labels: under review

#2270 fix(foot-shooting): remove leftover code that panics via RPC
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher_legacy.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
Labels: under review

#2264 fix(hd-wallet): correctly display evm addr in `get_new_address` response
  mm2src/coins/rpc_command/get_new_address.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
Labels: P1, under review

#2272 fix(healthchecks): use safer subtraction on expiration
  mm2src/mm2_main/src/lp_healthcheck.rs
Labels: under review

#2141 feat(tokens): custom token activation for evm
  mm2src/coins/eth.rs
  mm2src/coins/eth/erc20.rs
  mm2src/coins/eth/eth_balance_events.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/z_coin.rs
  mm2src/coins_activation/src/erc20_token_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/init_erc20_token_activation.rs
  mm2src/coins_activation/src/init_token.rs
  mm2src/coins_activation/src/l2/init_l2.rs
  mm2src/coins_activation/src/l2/init_l2_error.rs
  mm2src/coins_activation/src/platform_coin_with_tokens.rs
  mm2src/coins_activation/src/prelude.rs
  mm2src/coins_activation/src/slp_token_activation.rs
  mm2src/coins_activation/src/standalone_coin/init_standalone_coin.rs
  mm2src/coins_activation/src/standalone_coin/init_standalone_coin_error.rs
  mm2src/coins_activation/src/tendermint_token_activation.rs
  mm2src/coins_activation/src/token.rs
  mm2src/mm2_bin_lib/src/mm2_native_lib.rs
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher_legacy.rs
  mm2src/mm2_main/src/rpc/lp_commands/db_id.rs
  mm2src/mm2_main/src/rpc/lp_commands/legacy.rs
  mm2src/mm2_main/src/rpc/lp_commands/mod.rs
  mm2src/mm2_main/src/rpc/lp_commands/pubkey.rs
  mm2src/mm2_main/src/rpc/lp_commands/tokens.rs
  mm2src/mm2_main/src/rpc/lp_commands/trezor.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: P1, QA, under review, docs

#2240 chore(release): add changelog entries for v2.2.0-beta
  CHANGELOG.md
Labels: under review

#2277 chore(release): update v2.2.0-beta date
  CHANGELOG.md
Labels: under review
