Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-02, with the labels that each got.

#1960 refactor(utxo): refactor utxo output script creation
  mm2src/coins/coin_errors.rs
  mm2src/coins/lightning/ln_events.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/qrc20/script_pubkey.rs
  mm2src/coins/rpc_command/init_scan_for_new_addresses.rs
  mm2src/coins/rpc_command/lightning/open_channel.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/utxo_balance_events.rs
  mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_builder/utxo_conf_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common/utxo_tx_history_v2_common.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_withdraw.rs
  mm2src/coins/utxo_signer/src/with_key_pair.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_htlc.rs
  mm2src/mm2_bitcoin/keys/src/address.rs
  mm2src/mm2_bitcoin/keys/src/address/address_builder.rs
  mm2src/mm2_bitcoin/keys/src/address_prefixes.rs
  mm2src/mm2_bitcoin/keys/src/cashaddress.rs
  mm2src/mm2_bitcoin/keys/src/error.rs
  mm2src/mm2_bitcoin/keys/src/legacyaddress.rs
  mm2src/mm2_bitcoin/keys/src/lib.rs
  mm2src/mm2_bitcoin/keys/src/segwitaddress.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/address.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/mod.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/transaction.rs
  mm2src/mm2_bitcoin/script/src/builder.rs
  mm2src/mm2_bitcoin/script/src/script.rs
  mm2src/mm2_bitcoin/script/src/sign.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: under review, 2.1.0-beta, sec-review, no-deps

#2039 feat(nft): nft abi in withdraw_nft RPC, clear_nft_db RPC
  Cargo.lock
  Cargo.toml
  mm2src/coins/Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/hd_confirm_address.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/mod.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/coins/rpc_command/get_new_address.rs
  mm2src/coins/rpc_command/init_create_account.rs
  mm2src/crypto/Cargo.toml
  mm2src/crypto/src/shared_db_id.rs
  mm2src/db_common/src/sqlite.rs
  mm2src/derives/enum_derives/Cargo.toml
  mm2src/derives/enum_derives/src/from_inner.rs
  mm2src/derives/enum_derives/src/from_stringify.rs
  mm2src/derives/enum_derives/src/from_trait.rs
  mm2src/derives/enum_derives/src/lib.rs
  mm2src/mm2_db/Cargo.toml
  mm2src/mm2_db/src/indexed_db/drivers/cursor/cursor.rs
  mm2src/mm2_db/src/indexed_db/drivers/transaction.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_init/init_hw.rs
  mm2src/mm2_main/src/lp_init/init_metamask.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
Labels: QA, under review, sec-review, docs, no-deps

#1953 fix(wasm worker env): refactor direct usage of `window`
  mm2src/mm2_db/src/indexed_db/drivers/builder.rs
  mm2src/mm2_db/src/indexed_db/indexed_db.rs
  mm2src/mm2_net/src/wasm_http.rs
Labels: bug, under review, 2.1.0-beta

#2027 fix(makerbot): allow more than one prices url in makerbot
  mm2src/coins/lp_price.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/lp_bot.rs
  mm2src/mm2_main/src/lp_ordermatch/simple_market_maker.rs
Labels: QA, under review, 2.1.0-beta, docs

#2062 deps(network): security bump for `h2`
  Cargo.lock
  mm2src/adex_cli/Cargo.lock
Labels: under review

#2028 fix(indexeddb): fix IDB cursor.continue_() call after drop
  mm2src/coins/utxo/utxo_block_header_storage/wasm/indexeddb_block_header_storage.rs
  mm2src/mm2_db/src/indexed_db/drivers/cursor/cursor.rs
  mm2src/mm2_db/src/indexed_db/indexed_cursor.rs
Labels: under review

#2061 feat(stats_swaps): add gui version in status db
  mm2src/mm2_main/src/database.rs
  mm2src/mm2_main/src/database/stats_swaps.rs
Labels: under review

#2063 feat(config): add `max_concurrent_connections` to mm2
  Cargo.lock
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/behaviours/mod.rs
Labels: under review

#2067 fix(indexeddb): set stop on success cursor condition
  mm2src/mm2_db/src/indexed_db/drivers/cursor/cursor.rs
Labels: under review

#2058 feat(ETH transport & heartbeats): various enhancements/features
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_balance_events.rs
  mm2src/coins/eth/eth_rpc.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/eth/web3_transport/metamask_transport.rs
  mm2src/coins/eth/web3_transport/mod.rs
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/coins/nft.rs
  mm2src/coins_activation/src/erc20_token_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/common/Cargo.toml
  mm2src/common/common.rs
  mm2src/common/expirable_map.rs
  mm2src/common/time_cache.rs
  mm2src/mm2_main/src/heartbeat_event.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_net/src/transport.rs
Labels: enhancement, under review
