Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-10, with the labels that each got.

#2233 fix(proxy-signature): add message lifetime overflows
  mm2src/proxy_signature/src/lib.rs
Labels: enhancement, under review

#2234 chore(adex-cli): deprecate adex-cli
  .github/workflows/adex-cli.yml
  mm2src/adex_cli/README.md
Labels: under review

#2199 fix(legacy-swap): taker failed spend maker payment marked as failed
  mm2src/mm2_main/src/for_tests/iris_nimda_rick_taker_swap.json
  mm2src/mm2_main/src/for_tests/recreate_maker_swap_maker_payment_wait_confirm_failed_taker_saved.json
  mm2src/mm2_main/src/for_tests/recreate_maker_swap_taker_saved.json
  mm2src/mm2_main/src/for_tests/recreate_taker_swap_taker_expected.json
  mm2src/mm2_main/src/for_tests/recreate_taker_swap_taker_payment_wait_confirm_failed_taker_expected.json
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/recreate_swap_data.rs
  mm2src/mm2_main/src/lp_swap/taker_restart.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/docker_tests/swaps_file_lock_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review

#2232 fix(orders): fix cancel order race condition using time-based cache
  Cargo.lock
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/common/expirable_map.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/data_asker.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_healthcheck.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_p2p/src/lib.rs
Labels: under review

#2235 chore(cli): remove leftover subcommands from help message
  mm2src/mm2_main/src/mm2.rs
Labels: under review

#2239 chore(solana): remove solana implementation
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_coins.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/solana_common.rs
  mm2src/coins/solana/solana_common_tests.rs
  mm2src/coins/solana/solana_decode_tx_helpers.rs
  mm2src/coins/solana/solana_tests.rs
  mm2src/coins/solana/spl.rs
  mm2src/coins/solana/spl_tests.rs
  mm2src/coins_activation/Cargo.toml
  mm2src/coins_activation/src/lib.rs
  mm2src/coins_activation/src/solana_with_tokens_activation.rs
  mm2src/coins_activation/src/spl_token_activation.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/mod.rs
  mm2src/mm2_main/tests/docker_tests/solana_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: under review

#2238 fix(cosmos): fix tx broadcasting error
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/tendermint/htlc/iris/htlc.rs
  mm2src/coins/tendermint/htlc/nucleus/htlc.rs
  mm2src/coins/tendermint/ibc/mod.rs
  mm2src/coins/tendermint/ibc/transfer_v1.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/utxo/pb.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_swap/komodefi.swap_v2.pb.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/trezor/Cargo.toml
  mm2src/trezor/src/error.rs
  mm2src/trezor/src/response.rs
  mm2src/trezor/src/transport/protocol.rs
  mm2src/trezor/src/utxo/sign_utxo.rs
Labels: bug, under review

#2246 feat(cosmos-offline-tests): prepare IBC channels inside the container
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
Labels: enhancement, CI, under review

#2248 chore(old-network-stack): remove old p2p implementation
  Cargo.toml
  mm2src/floodsub/CHANGELOG.md
  mm2src/floodsub/Cargo.toml
  mm2src/floodsub/build.rs
  mm2src/floodsub/src/layer.rs
  mm2src/floodsub/src/lib.rs
  mm2src/floodsub/src/protocol.rs
  mm2src/floodsub/src/rpc.proto
  mm2src/floodsub/src/topic.rs
  mm2src/gossipsub/CHANGELOG.md
  mm2src/gossipsub/Cargo.toml
  mm2src/gossipsub/build.rs
  mm2src/gossipsub/src/behaviour.rs
  mm2src/gossipsub/src/behaviour/tests.rs
  mm2src/gossipsub/src/config.rs
  mm2src/gossipsub/src/handler.rs
  mm2src/gossipsub/src/lib.rs
  mm2src/gossipsub/src/mcache.rs
  mm2src/gossipsub/src/protocol.rs
  mm2src/gossipsub/src/rpc.proto
  mm2src/gossipsub/src/topic.rs
  mm2src/gossipsub/tests/smoke.rs
  mm2src/mm2_libp2p/Cargo.toml
  mm2src/mm2_libp2p/src/adex_ping.rs
  mm2src/mm2_libp2p/src/atomicdex_behaviour.rs
  mm2src/mm2_libp2p/src/atomicdex_behaviour/tests.rs
  mm2src/mm2_libp2p/src/lib.rs
  mm2src/mm2_libp2p/src/network.rs
  mm2src/mm2_libp2p/src/peers_exchange.rs
  mm2src/mm2_libp2p/src/relay_address.rs
  mm2src/mm2_libp2p/src/request_response.rs
  mm2src/mm2_libp2p/src/runtime.rs
Labels: under review

#2250 refactor(SwapOps): make `send_maker_payment` async
  mm2src/coins/eth.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/siacoin.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: under review

#2251 refactor(SwapOps): make all methods async
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/siacoin.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: under review

#1966 feat(utxo): prioritize electrum connections
  mm2src/adex_cli/Cargo.lock
  mm2src/adex_cli/Cargo.toml
  mm2src/adex_cli/src/adex_proc/adex_proc_impl.rs
  mm2src/adex_cli/src/rpc_data.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/coins/lightning/ln_platform.rs
  mm2src/coins/lightning/ln_utils.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/client.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection_manager/connection_context.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection_manager/manager.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection_manager/mod.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/constants.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/event_handlers.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/mod.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/rpc_responses.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/tcp_stream.rs
  mm2src/coins/utxo/utxo_balance_events.rs
  mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_wasm_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/common/common.rs
  mm2src/common/executor/abortable_system/abortable_queue.rs
  mm2src/common/executor/abortable_system/graceful_shutdown.rs
  mm2src/common/executor/abortable_system/mod.rs
  mm2src/common/executor/abortable_system/simple_map.rs
  mm2src/common/expirable_map.rs
  mm2src/common/jsonrpc_client.rs
  mm2src/common/notifier.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_net/src/sse_handler.rs
  mm2src/mm2_net/src/wasm/wasm_ws.rs
Labels: under review, docs, 2.2.0-beta

#2254 fix(evm): correctly display eth addr in iguana v2 activation result
  mm2src/coins_activation/src/eth_with_token_activation.rs
Labels: under review

#2256 refactor(P2P): types and modules
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/coins/nft.rs
  mm2src/coins/tendermint/rpc/tendermint_native_rpc.rs
  mm2src/coins/tendermint/rpc/tendermint_wasm_rpc.rs
  mm2src/coins/tendermint/tendermint_balance_events.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_healthcheck.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/best_orders.rs
  mm2src/mm2_main/src/lp_ordermatch/orderbook_depth.rs
  mm2src/mm2_main/src/lp_stats.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/lib.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/application/mod.rs
  mm2src/mm2_p2p/src/application/network_event.rs
  mm2src/mm2_p2p/src/application/request_response/mod.rs
  mm2src/mm2_p2p/src/application/request_response/network_info.rs
  mm2src/mm2_p2p/src/application/request_response/ordermatch.rs
  mm2src/mm2_p2p/src/lib.rs
  mm2src/mm2_p2p/src/p2p_ctx.rs
Labels: Refactoring, under review
