Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-08, with the labels that each got.

#2184 fix(zcoin): don't force low r signing to generate htlc pubkey for zcoin
  mm2src/coins/utxo_signer/src/with_key_pair.rs
  mm2src/mm2_bitcoin/keys/src/keypair.rs
  mm2src/mm2_bitcoin/keys/src/private.rs
  mm2src/mm2_bitcoin/script/src/sign.rs
Labels: under review

#2165 chore(release): add changelog entries for v2.1.0-beta
  CHANGELOG.md
Labels: under review

#2129 feat(nft-swap): complete refund methods
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_swap_v2.rs
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/coins/eth/for_tests.rs
  mm2src/coins/eth/maker_swap_v2_abi.json
  mm2src/coins/eth/nft_swap_v2/mod.rs
  mm2src/coins/eth/taker_swap_v2_abi.json
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/eth/web3_transport/mod.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins_activation/src/erc20_token_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/prelude.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_test_helpers/contract_bytes/erc1155_test_token_bytes
  mm2src/mm2_test_helpers/contract_bytes/erc20_token_bytes
  mm2src/mm2_test_helpers/contract_bytes/erc721_test_token_bytes
  mm2src/mm2_test_helpers/contract_bytes/maker_swap_v2_bytes
  mm2src/mm2_test_helpers/contract_bytes/nft_maker_swap_v2_bytes
  mm2src/mm2_test_helpers/contract_bytes/nft_swap_contract_bytes
  mm2src/mm2_test_helpers/contract_bytes/swap_contract_bytes
  mm2src/mm2_test_helpers/contract_bytes/taker_swap_v2_bytes
  mm2src/mm2_test_helpers/contract_bytes/watchers_swap_contract_bytes
Labels: under review, docs, 2.2.0-beta

#2185 ci(docker-tests): ignore tendermint IBC tests for now
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
Labels: under review

#2188 chore(release): bump mm2 version to 2.2.0-beta
  Cargo.lock
  mm2src/mm2_bin_lib/Cargo.toml
Labels: under review

#2173 feat(cosmos): komodo-defi-proxy support
  Cargo.lock
  Cargo.toml
  mm2src/coins/Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/eth/for_tests.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/eth/web3_transport/mod.rs
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/tendermint/rpc/tendermint_native_rpc.rs
  mm2src/coins/tendermint/rpc/tendermint_wasm_rpc.rs
  mm2src/coins/tendermint/tendermint_balance_events.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins_activation/src/erc20_token_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/common/Cargo.toml
  mm2src/common/common.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/p2p.rs
  mm2src/mm2_net/src/transport.rs
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/lib.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/proxy_signature/Cargo.toml
  mm2src/proxy_signature/src/lib.rs
Labels: enhancement, QA, under review, docs, 2.2.0-beta

#2193 docs(README): update commit badges to use dev branch
  README.md
Labels: under review

#2191 fix(cors): allow OPTIONS request to KDF server
  .github/workflows/test.yml
  mm2src/mm2_main/src/rpc.rs
Labels: under review, 2.2.0-beta

#2169 feat(eth-swap): eth tpu v2 methods, eth docker test enhancements
  mm2src/coins/coin_errors.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_swap_v2.rs
  mm2src/coins/eth/nft_swap_v2/errors.rs
  mm2src/coins/eth/nft_swap_v2/mod.rs
  mm2src/coins/eth/nft_swap_v2/structs.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_test_helpers/contract_bytes/maker_swap_v2_bytes
  mm2src/mm2_test_helpers/contract_bytes/nft_maker_swap_v2_bytes
  mm2src/mm2_test_helpers/contract_bytes/nft_swap_contract_bytes
  mm2src/mm2_test_helpers/contract_bytes/taker_swap_v2_bytes
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/proxy_signature/src/lib.rs
Labels: under review

#2167 feat(sia): extract sia lib to external repo
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/hd_wallet/pubkey.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/sia/address.rs
  mm2src/coins/sia/blake2b_internal.rs
  mm2src/coins/sia/encoding.rs
  mm2src/coins/sia/http_client.rs
  mm2src/coins/sia/spend_policy.rs
  mm2src/coins/siacoin.rs
  mm2src/coins/siacoin/sia_hd_wallet.rs
  mm2src/coins_activation/src/prelude.rs
  mm2src/coins_activation/src/sia_coin_activation.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/mod.rs
  mm2src/mm2_main/tests/docker_tests/sia_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
  mm2src/mm2_main/tests/docker_tests_sia_unique.rs
Labels: under review

#2204 chore(test): turn on debug assertion
  Cargo.toml
  mm2src/coins/z_coin/storage.rs
Labels: under review
