Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-09, with the labels that each got.

#2210 fix(coins): add p2p feature to mm2_net dependency
  mm2src/coins/Cargo.toml
Labels: under review

#2200 chore(WASM-builds): remove `wasm-opt` overriding
  mm2src/mm2_bin_lib/Cargo.toml
Labels: under review

#2195 chore(RPCs): rename `get_peers_info` RPC to `get_directly_connected_peers`
  mm2src/mm2_libp2p/src/atomicdex_behaviour.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher_legacy.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
  mm2src/mm2_net/src/network_event.rs
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/lib.rs
Labels: technical debt, QA, breaking-change, docs

#2218 fix(db): stop creating the all-zeroes dir on KDF start
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/lp_native_dex.rs
Labels: under review

#2212 docs(README): fix typos
  README.md
Labels: under review

#2213 feat(core): handling CTRL-C signal with graceful shutdown
  Cargo.toml
  mm2src/mm2_bin_lib/src/lib.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/rpc/lp_commands/lp_commands_legacy.rs
Labels: enhancement, QA, under review, 2.2.0-beta

#2224 fix(clippy): fix coins mod clippy warnings in wasm
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/z_coin/storage/walletdb/wasm/mod.rs
Labels: under review

#2219 fix(native-rpc): remove escaped response body
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/rpc.rs
Labels: under review, 2.2.0-beta

#2220 chore(tests): don't use `.wait()` and use `block_on` instead
  clippy.toml
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning/ln_platform.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/solana/solana_tests.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/common/common.rs
  mm2src/mm2_err_handle/src/map_to_mm_fut.rs
  mm2src/mm2_err_handle/src/mm_error.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: under review

#2229 fix(merge): remove duplicated `db_root` function
  mm2src/mm2_core/src/mm_ctx.rs
Labels: under review

#2227 chore(doc): update issue address in README
  README.md
Labels: documentation, under review, 2.2.0-beta

#2217 feat(CI): handle remote files in a safer way
  .github/actions/deps-install/action.yml
  .github/actions/download-and-verify/action.yml
  .github/workflows/test.yml
Labels: CI, under review
