Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-12, with the labels that each got.

#2222 feat(LRAPI): add 1inch classic swap rpc
  Cargo.lock
  Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/eth/eip1559_gas_fee.rs
  mm2src/coins/eth/eth_rpc.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/get_estimated_fees.rs
  mm2src/common/Cargo.toml
  mm2src/common/common.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/ext_api.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/src/rpc/lp_commands/mod.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/errors.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/rpcs.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/types.rs
  mm2src/mm2_main/src/rpc/lp_commands/tokens.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/trading_api/Cargo.toml
  mm2src/trading_api/src/lib.rs
  mm2src/trading_api/src/one_inch_api.rs
  mm2src/trading_api/src/one_inch_api/client.rs
  mm2src/trading_api/src/one_inch_api/errors.rs
  mm2src/trading_api/src/one_inch_api/types.rs
Labels: QA, under review, docs, 2.3.0-beta

#2288 improvement(error-handling): main files
  .github/workflows/pr-lint.yml
  mm2src/common/common.rs
  mm2src/mm2_main/src/mm2.rs
Labels: under review, improvement:error-handling

#2289 fix(mm2_bitcoin): don't rely on `core`
  mm2src/mm2_bitcoin/rpc/src/lib.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/bytes.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/hash.rs
Labels: under review

#2267 chore(ctx): replace gstuff constructible with oncelock
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/hd_wallet/storage/sqlite_storage.rs
  mm2src/coins/lightning/ln_utils.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/tx_history_storage/sql_tx_history_storage_v2.rs
  mm2src/coins/utxo/utxo_block_header_storage/mod.rs
  mm2src/coins/z_coin/storage/blockdb/blockdb_sql_storage.rs
  mm2src/crypto/src/crypto_ctx.rs
  mm2src/mm2_bin_lib/src/lib.rs
  mm2src/mm2_bin_lib/src/mm2_wasm_lib.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_gui_storage/src/account/storage/sqlite_storage.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_wallet.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_storage.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_wasm_db.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, 2.3.0-beta

#2290 chore(adex-cli): use "Komodo DeFi Framework" name in adex_cli
  mm2src/adex_cli/src/scenarios/init_mm2_cfg.rs
Labels: under review

#2296 chore(libp2p): k-0.52.11 bump
  Cargo.lock
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_p2p/Cargo.toml
  mm2src/proxy_signature/Cargo.toml
Labels: improvement: resource usage, improvement: security, status: pending review, priority: urgent

#2284 chore(release): v2.3.0-beta
  .github/workflows/pr-lint.yml
  Cargo.lock
  Cargo.toml
  mm2src/adex_cli/src/scenarios/init_mm2_cfg.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/eip1559_gas_fee.rs
  mm2src/coins/eth/eth_rpc.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/hd_wallet/storage/sqlite_storage.rs
  mm2src/coins/lightning/ln_utils.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/rpc_command/get_estimated_fees.rs
  mm2src/coins/tx_history_storage/sql_tx_history_storage_v2.rs
  mm2src/coins/utxo/utxo_block_header_storage/mod.rs
  mm2src/coins/z_coin/storage/blockdb/blockdb_sql_storage.rs
  mm2src/common/Cargo.toml
  mm2src/common/common.rs
  mm2src/crypto/src/crypto_ctx.rs
  mm2src/mm2_bin_lib/Cargo.toml
  mm2src/mm2_bin_lib/src/lib.rs
  mm2src/mm2_bin_lib/src/mm2_wasm_lib.rs
  mm2src/mm2_bitcoin/rpc/src/lib.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/bytes.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/hash.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_gui_storage/src/account/storage/sqlite_storage.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/ext_api.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_wallet.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_storage.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_wasm_db.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/src/rpc/lp_commands/mod.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/errors.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/rpcs.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/types.rs
  mm2src/mm2_main/src/rpc/lp_commands/tokens.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/proxy_signature/Cargo.toml
  mm2src/trading_api/Cargo.toml
  mm2src/trading_api/src/lib.rs
  mm2src/trading_api/src/one_inch_api.rs
  mm2src/trading_api/src/one_inch_api/client.rs
  mm2src/trading_api/src/one_inch_api/errors.rs
  mm2src/trading_api/src/one_inch_api/types.rs
Labels: status: pending review

#2255 feat(p2p): ensure time synchronization in the network
  Cargo.lock
  mm2src/common/Cargo.toml
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_stats.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/application/request_response/network_info.rs
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/behaviours/mod.rs
  mm2src/mm2_p2p/src/behaviours/peers_exchange.rs
Labels: 2.4.0-beta, status: pending review, feature: P2P

#2302 chore(p2p): follow-up nits
  mm2src/coins/Cargo.toml
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
Labels: status: pending review, improvement: P2P

#2294 chore(ci): Update docker build for wasm
  .docker/Dockerfile
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  .github/workflows/test.yml
  docs/WASM_BUILD.md
Labels: status: pending review, improvement: CI

#2295 fix(wasm): add test-ext-api feature to mm2_main and mm2_bin_lib tomls
  .github/workflows/pr-lint.yml
  mm2src/mm2_bin_lib/Cargo.toml
  mm2src/mm2_main/Cargo.toml
Labels: status: pending review

#2303 improvement(CI): switch to proper rust caching
  .github/actions/build-cache/action.yml
  .github/actions/cargo-cache/action.yml
  .github/workflows/dev-build.yml
  .github/workflows/fmt-and-lint.yml
  .github/workflows/release-build.yml
  .github/workflows/test.yml
  mm2src/coins/eth/eth_tests.rs
  mm2src/trading_api/src/one_inch_api/client.rs
  mm2src/trading_api/src/one_inch_api/errors.rs
Labels: status: pending review, improvement: CI

#2291 chore(eth-websocket): remove some unnecessary wrappers
  mm2src/coins/eth/web3_transport/websocket_transport.rs
Labels: status: pending review

#2305 chore(cosmos-tests): update broken RPC URL
  mm2src/coins/tendermint/rpc/tendermint_wasm_rpc.rs
Labels: status: pending review

#2306 fix(timed-map): missing feature for WASM
  mm2src/mm2_p2p/Cargo.toml
Labels: status: pending review

#2307 chore(CI): unlock wasm-pack version
  .docker/Dockerfile
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  docs/WASM_BUILD.md
Labels: status: pending review

#2308 fix(deps): add the web-time package to Cargo.lock
  Cargo.lock
Labels: status: pending review
