Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-07, with the labels that each got.

#2148 feat(tendermint): support unsigned txs for ledger's keplr extension
  mm2src/coins/tendermint/htlc/mod.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
Labels: enhancement, under review, 2.1.0-beta

#2153 fix(restrictions): remove wallet-only restriction from max_maker_vol
  mm2src/mm2_main/src/lp_swap/max_maker_vol_rpc.rs
Labels: under review

#2126 chore(bin): rename mm2 binaries to kdf
  .docker/Dockerfile.dev-release
  .docker/Dockerfile.release
  .docker/Dockerfile.ubuntu.ci
  .dockerignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  .github/workflows/test.yml
  .github/workflows/validate-mm2-version.yml
  .gitignore
  README.md
  mm2src/mm2_bin_lib/Cargo.toml
  mm2src/mm2_main/src/mm2.rs
  scripts/mm2/client/client
  scripts/mm2/client/client_debug
  scripts/mm2/seed/run
  scripts/mm2/seed/run_debug
Labels: under review, breaking-change

#2157 fix(ci-builds): use ssh-deploy action for all builds except windows
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
Labels: under review

#2158 ci(artifacts): upload build artifacts with in-tree script
  .docker/Dockerfile.ci-container
  .github/actions/deps-install/action.yml
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  scripts/ci/upload_artifact.py
Labels: enhancement, under review

#2160 ci(artifact): fix upload bug
  scripts/ci/upload_artifact.py
Labels: under review

#2155 feat(tendermint): improve the `max` handling for tendermint withdraw
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
Labels: P0, under review

#2162 fix(docker-tests): implement containers runtime directories
  .gitignore
  mm2src/mm2_io/src/fs.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
Labels: under review

#2161 fix(makerbot): add "testcoin" to provider options
  mm2src/coins/lp_price.rs
Labels: under review, 2.1.0-beta

#2166 fix(helpers): extend http to ws address conversion
  mm2src/coins/tendermint/tendermint_balance_events.rs
  mm2src/common/common.rs
Labels: under review

#2163 ci(artifact): add target for macos on apple silicon
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
Labels: under review

#2164 feat(tendermint): implement better sequence resolving logic
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
Labels: enhancement, under review

#2137 feat(ETH): add gas_limit coins param to override default values
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/for_tests.rs
  mm2src/coins/eth/nft_swap_v2/mod.rs
  mm2src/coins/eth/v2_activation.rs
Labels: P1, QA, under review, 2.1.0-beta, docs

#2100 feat(nft-swap): add standalone maker contract and proxy support
  mm2src/coins/eth.rs
  mm2src/coins/eth/nft_maker_swap_v2_abi.json
  mm2src/coins/eth/nft_swap_v2/mod.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/eth/web3_transport/http_transport.rs
  mm2src/coins/eth/web3_transport/mod.rs
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/utxo/utxo_builder/utxo_conf_builder.rs
  mm2src/coins_activation/src/erc20_token_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/init_erc20_token_activation.rs
  mm2src/coins_activation/src/token.rs
  mm2src/common/common.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
  mm2src/mm2_net/src/native_http.rs
  mm2src/mm2_net/src/transport.rs
  mm2src/mm2_net/src/wasm/http.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: QA, under review, docs

#2176 fix(swaps): ensure taker payment spend confirmations
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
Labels: P0, in progress, 2.1.0-beta

#2177 chore(cargo-config): migrate to `config.toml` to avoid warning
  .cargo/config.toml
Labels: under review

#2179 chore(rust-analyzer): add rust-analyzer into the workspace toolchain
  rust-toolchain.toml
Labels: under review
