Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-03, with the labels that each got.

#2049 feat(nft): enable eth with non fungible tokens
  Cargo.lock
  mm2src/coins/coin_errors.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/storage/wasm/mod.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins_activation/Cargo.toml
  mm2src/coins_activation/src/bch_with_tokens_activation.rs
  mm2src/coins_activation/src/erc20_token_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/coins_activation/src/platform_coin_with_tokens.rs
  mm2src/coins_activation/src/prelude.rs
  mm2src/coins_activation/src/solana_with_tokens_activation.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/coins_activation/src/token.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap/check_balance.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
Labels: QA, under review, 2.1.0-beta, sec-review, docs

#2074 feat(network): improve efficiency of known peers handling
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/behaviours/peers_exchange.rs
  mm2src/mm2_p2p/src/behaviours/request_response.rs
Labels: P2, under review

#2078 fix(utxo): fix test_hd_utxo_tx_history unit test
  mm2src/coins/for_tests/DOC_HD_tx_history_fixtures.json
  mm2src/coins/for_tests/MORTY_HD_tx_history_fixtures.json
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_wasm_tests.rs
Labels: under review

#2080 feat(event streaming): configurable worker path, use SharedWorker
  mm2src/mm2_event_stream/src/lib.rs
  mm2src/mm2_net/Cargo.toml
  mm2src/mm2_net/src/wasm_event_stream.rs
Labels: enhancement, under review

#2082 chore(ci/cd): update dockerhub destination repository
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
Labels: under review

#2066 feat(indexeddb): advanced cursor filtering impl
  mm2src/mm2_db/src/indexed_db/drivers/cursor/cursor.rs
  mm2src/mm2_db/src/indexed_db/indexed_cursor.rs
  mm2src/mm2_db/src/indexed_db/indexed_db.rs
Labels: under review

#2077 feat(zcoin): impl tx_history support for WASM target
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage/walletdb/wasm/storage.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_tx_history.rs
  mm2src/mm2_db/src/indexed_db/indexed_cursor.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/src/wasm_tests.rs
Labels: under review

#2076 feat(zcoin): impl balance event streaming
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage.rs
  mm2src/coins/z_coin/storage/blockdb/blockdb_idb_storage.rs
  mm2src/coins/z_coin/storage/blockdb/blockdb_sql_storage.rs
  mm2src/coins/z_coin/storage/z_params/indexeddb.rs
  mm2src/coins/z_coin/storage/z_params/mod.rs
  mm2src/coins/z_coin/z_balance_streaming.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_rpc.rs
Labels: QA, under review, 2.1.0-beta, sec-review, no-deps
