Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2024-06, with the labels that each got.

#2131 fix(indexeddb): window usage in worker env
  mm2src/mm2_db/src/indexed_db/indexed_db.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: under review, 2.1.0-beta

#2144 fix(docs): update cargo test command
  docs/DEV_ENVIRONMENT.md
Labels: under review

#2091 feat(solana-swap): solana swap protocol v1 POC
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_coins.rs
  mm2src/coins/solana.rs
  mm2src/coins/solana/solana_common_tests.rs
  mm2src/coins/solana/solana_tests.rs
  mm2src/mm2_main/src/lp_swap.rs
Labels: under review

#2149 chore(toolchain): upgrade to 1.72 nightly
  .docker/Dockerfile
  .github/workflows/dev-build.yml
  .github/workflows/fmt-and-lint.yml
  .github/workflows/release-build.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  docs/ANDROID_CROSS_ON_M1_MAC.md
  docs/DEV_ENVIRONMENT.md
  docs/WASM_BUILD.md
  mm2src/adex_cli/Cargo.lock
  mm2src/adex_cli/Cargo.toml
  mm2src/coins/coin_balance.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/hd_wallet/coin_ops.rs
  mm2src/coins/lightning/ln_sql.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/lp_price.rs
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/utxo/rpc_clients.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage/blockdb/blockdb_sql_storage.rs
  mm2src/coins/z_coin/storage/walletdb/wasm/mod.rs
  mm2src/common/common.rs
  mm2src/common/crash_reports.rs
  mm2src/common/custom_futures/repeatable.rs
  mm2src/common/log/native_log.rs
  mm2src/db_common/src/sqlite.rs
  mm2src/mm2_bitcoin/chain/src/transaction.rs
  mm2src/mm2_bitcoin/crypto/src/lib.rs
  mm2src/mm2_bitcoin/keys/src/address.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/address.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/bytes.rs
  mm2src/mm2_core/src/event_dispatcher.rs
  mm2src/mm2_core/src/lib.rs
  mm2src/mm2_db/src/indexed_db/indexed_cursor.rs
  mm2src/mm2_db/src/indexed_db/indexed_db.rs
  mm2src/mm2_main/src/database/stats_nodes.rs
  mm2src/mm2_main/src/lib.rs
  mm2src/mm2_main/src/lp_stats.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_net/src/sse_handler.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_rpc/src/data/legacy/activation/utxo.rs
  mm2src/mm2_rpc/src/data/legacy/orders.rs
  rust-toolchain.toml
Labels: enhancement, under review
