Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-08, with the labels that each got.

#2562 improvement(dep-stack): security bumps
  Cargo.lock
  Cargo.toml
  mm2src/coins/Cargo.toml
  mm2src/coins/qrc20.rs
  mm2src/coins/tendermint/ibc/transfer_v1.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/common/common.rs
  mm2src/mm2_bin_lib/Cargo.toml
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_test_helpers/Cargo.toml
Labels: improvement: security, status: pending review, bug: security

#2583 fix(utxo): fix header deserialization; guard AuxPoW
  mm2src/coins/utxo/rpc_clients/electrum_rpc/client.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/mm2_bitcoin/chain/src/block_header.rs
  mm2src/mm2_bitcoin/serialization/src/reader.rs
Labels: status: pending review

#2565 fix(Trezor): fix utxo and eth calls due to firmware changes
  Cargo.lock
  mm2src/coins/hd_wallet/confirm_address.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/get_new_address.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/trezor/Cargo.toml
  mm2src/trezor/src/eth/eth_command.rs
  mm2src/trezor/src/proto/messages_ethereum.rs
  mm2src/trezor/src/utxo/utxo_command.rs
Labels: priority: high, bug: core, 2.6.0-beta

#2589 fix(clippy): fix clippy warnings for #2565
  Cargo.lock
  mm2src/trezor/src/proto/messages_ethereum.rs
Labels: status: pending review

#2607 ci(wasm): add GHA to deploy wasm playground previews on PRs
  .github/workflows/dev-build.yml
  .github/workflows/pr-wasm-preview.yml
  .github/workflows/release-build.yml
Labels: feature: CI, deploy: wasm-playground

#2587 feat(utxo): introduce a utxo consolidation rpc
  mm2src/coins/rpc_command/consolidate_utxos.rs
  mm2src/coins/rpc_command/fetch_utxos.rs
  mm2src/coins/rpc_command/mod.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/utxo_builder/mod.rs
  mm2src/coins/utxo/utxo_builder/utxo_arc_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/common/common.rs
  mm2src/common/log.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_test_helpers/src/structs.rs
Labels: status: pending review, feature: API, status: pending docs
