Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-02, with the labels that each got.

#2279 fix(hash-types): remove panic, enforce fixed-size arrays
  mm2src/coins/eth.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lightning/ln_platform.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/history.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/qrc20/swap.rs
  mm2src/coins/siacoin.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/bchd_grpc.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/rpc_responses.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_wasm_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/z_tx_history.rs
  mm2src/crypto/src/hw_ctx.rs
  mm2src/crypto/src/privkey.rs
  mm2src/mm2_bitcoin/crypto/src/lib.rs
  mm2src/mm2_bitcoin/keys/src/signature.rs
  mm2src/mm2_bitcoin/primitives/src/hash.rs
  mm2src/mm2_bitcoin/script/src/script.rs
  mm2src/mm2_bitcoin/script/src/sign.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/recreate_swap_data.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_restart.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: 2.4.0-beta, status: pending review, priority: high

#2333 fix(utxo-withdraw): get hw ctx only when `PrivKeyPolicy` is trezor
  mm2src/coins/utxo/utxo_withdraw.rs
Labels: 2.4.0-beta, status: pending review

#2330 feat(tendermint): unstaking/undelegation
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/tendermint/staking.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: 2.4.0-beta, feature: protocol

#2300 fix(tpu-v2): provide ethcoin support in tpu kickstart process
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_v2_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: 2.4.0-beta, priority: medium

#2261 fix(tpu-v2): fix tpu-v2 wait for payment spend and extract secret
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_swap_v2/eth_maker_swap_v2.rs
  mm2src/coins/eth/eth_swap_v2/eth_taker_swap_v2.rs
  mm2src/coins/eth/eth_swap_v2/mod.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/nft_swap_v2/mod.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/crypto/src/lib.rs
  mm2src/crypto/src/secret_hash_algo.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/recreate_swap_data.rs
  mm2src/mm2_main/src/lp_swap/swap_v2_common.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: 2.4.0-beta, status: pending review, priority: medium

#2317 feat(wallet): add change mnemonic password rpc
  mm2src/mm2_main/src/lp_wallet.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_wasm_db.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: 2.4.0-beta, status: pending review

#2324 feat(tpu-v2): provide swap protocol versioning
  mm2src/mm2_main/src/database.rs
  mm2src/mm2_main/src/database/my_swaps.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/my_orders_storage.rs
  mm2src/mm2_main/src/lp_ordermatch/new_protocol.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/swap_v2_rpcs.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_main/src/swap_versioning.rs
Labels: 2.4.0-beta, status: pending review, priority: high

#2346 chore(release): bump kdf version to 2.4.0-beta
  Cargo.lock
  mm2src/mm2_bin_lib/Cargo.toml
Labels: 2.4.0-beta, status: pending review

#2364 fix(fs): make `filter_files_by_extension` return only files
  mm2src/mm2_io/src/fs.rs
Labels: status: pending review, improvement: database

#2365 fix(tests): fix or ignore unstable tests
  .github/workflows/test.yml
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/z_coin/storage/blockdb/mod.rs
  mm2src/coins/z_coin/tx_streaming_tests/mod.rs
  mm2src/coins/z_coin/tx_streaming_tests/wasm.rs
  mm2src/common/common.rs
  mm2src/common/custom_futures/repeatable.rs
  mm2src/mm2_event_stream/src/manager.rs
  mm2src/mm2_main/src/wasm_tests.rs
  mm2src/mm2_main/tests/mm2_tests/bch_and_slp_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_net/src/native_http.rs
  mm2src/mm2_p2p/src/behaviours/mod.rs
  mm2src/mm2_test_helpers/src/electrums.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review

#2342 improvement(rpc-server): rpc server dynamic port allocation
  mm2src/mm2_bin_lib/src/lib.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/rpc.rs
Labels: status: in progress, improvement: RPC, 2.5.0-beta

#2334 fix(eth-tpu): remove state from funding validation
  mm2src/coins/coin_errors.rs
  mm2src/coins/eth/eth_swap_v2/eth_maker_swap_v2.rs
  mm2src/coins/eth/eth_swap_v2/eth_taker_swap_v2.rs
  mm2src/coins/eth/eth_swap_v2/mod.rs
  mm2src/coins/eth/nft_swap_v2/mod.rs
  mm2src/coins/lp_coins.rs
Labels: status: pending review, 2.5.0-beta

#2351 feat(tendermint): claim delegation rewards
  mm2src/coins/lp_coins.rs
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/rpc_command/tendermint/staking.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_test_helpers/dummy_files/nucleus-history.json
Labels: status: pending review, feature: protocol, feature: RPC, 2.5.0-beta

#2372 improvement(RPCs): group staking rpcs under a namespace
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/tendermint/staking.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review, improvement: RPC, breaking-change: RPC

#2373 fix(tests): stabilize `tendermint_coin::test_claim_staking_rewards`
  mm2src/coins/tendermint/tendermint_coin.rs
Labels: status: pending review, bug: tests

#2360 fix(key-derivation): use stored Argon2 parameters instead of default values
  mm2src/crypto/src/encrypt.rs
  mm2src/crypto/src/key_derivation.rs
  mm2src/crypto/src/mnemonic.rs
Labels: 2.4.0-beta, status: pending review
