Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-01, with the labels that each got.

#2311 fix(test): add feature to mm2_p2p dev build
  mm2src/coins/Cargo.toml
Labels: status: pending review

#2304 test(P2P): add test for peer time sync validation
  mm2src/common/Cargo.toml
  mm2src/common/common.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_p2p/Cargo.toml
Labels: status: pending review, improvement: tests

#2309 chore(CI): validate Cargo lock file
  .github/workflows/validate-cargo-lock.yml
Labels: status: pending review

#2310 feat(tendermint): validators RPC
  mm2src/coins/rpc_command/tendermint/mod.rs
  mm2src/coins/rpc_command/tendermint/staking.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review, feature: protocol, feature: RPC

#2283 fix(legacy_swap): check for existing maker/taker payment before timeout
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_restart.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
Labels: 2.4.0-beta, status: pending review

#2312 fix(crypto): allow non bip39 mnemonics storage
  mm2src/crypto/src/mnemonic.rs
  mm2src/mm2_main/src/lp_wallet.rs
Labels: status: pending review

#2319 refactor(build script): rewrite the main build script
  .dockerignore
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  .gitignore
  docs/ANDROID.md
  mm2src/mm2_bin_lib/build.rs
  mm2src/mm2_bin_lib/src/lib.rs
  mm2src/mm2_bin_lib/src/mm2_bin.rs
  mm2src/mm2_bin_lib/src/mm2_native_lib.rs
  mm2src/mm2_bin_lib/src/mm2_wasm_lib.rs
Labels: 2.4.0-beta, status: pending review, improvement: build time

#2326 chore(dep-bump): libp2p
  Cargo.lock
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_p2p/Cargo.toml
  mm2src/proxy_signature/Cargo.toml
Labels: status: pending review, improvement: build time

#2301 fix(mem-leak): `running_swap` never shrinks
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
Labels: status: pending review, priority: high

#2247 chore(deps): `timed-map` migration
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection.rs
  mm2src/common/common.rs
  mm2src/common/expirable_map.rs
  mm2src/common/time_cache.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/data_asker.rs
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_healthcheck.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
Labels: improvement: dependencies

#2322 feat(tendermint): staking/delegation
  mm2src/coins/hd_wallet/withdraw_ops.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/tendermint/staking.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review, feature: protocol, feature: RPC

#2276 fix(ARRR): store unconfirmed change output
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_htlc.rs
Labels: 2.4.0-beta, status: pending review
