Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-07, with the labels that each got.

#2524 chore(release): finalize changelog for v2.5.0-beta
  CHANGELOG.md
Labels: status: pending review

#2532 fix(eth): propagate structured EIP-1559 fee errors
  mm2src/coins/eth.rs
  mm2src/coins/lp_coins.rs
Labels: status: pending review, 2.6.0-beta

#2534 fix(WASM and Debian): fix build failures
  .docker/Dockerfile.ci-container
  mm2src/coins/z_coin/storage/blockdb/blockdb_idb_storage.rs
Labels: status: pending review

#2550 fix(DOC): improve docker tests start doc
  docs/DEV_ENVIRONMENT.md
Labels: status: pending review, priority: low, improvement: docs

#2552 fix(evm): support EIP55 (mixed case) & uncompressed pubkey exports
  mm2src/coins/rpc_command/offline_keys.rs
  mm2src/mm2_bin_lib/Cargo.toml
Labels: status: pending review

#2556 chore(release): propagate get_private_keys hotfix (staging→dev)
  Cargo.lock
  mm2src/coins/rpc_command/mod.rs
  mm2src/coins/rpc_command/offline_keys.rs
  mm2src/mm2_bin_lib/Cargo.toml
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review

#2560 chore(clippy): fix clippy warnings
  mm2src/coins/rpc_command/offline_keys.rs
Labels: status: pending review

#2538 improvement(walletconnect): return the `pairing_topic` in `new_connection` response
  mm2src/kdf_walletconnect/src/lib.rs
  mm2src/kdf_walletconnect/src/session/mod.rs
  mm2src/mm2_main/src/rpc/wc_commands/new_connection.rs
Labels: status: pending review, improvement: external wallets

#2468 ci(pull-requests): review notification bot
  .github/workflows/pr-lint.yml
  .github/workflows/pr-review-reminder.yml
Labels: feature: CI, 2.6.0-beta
