Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-05, with the labels that each got.

#2431 fix(event-streaming): initial addresses registration in utxo balance streaming
  mm2src/coins/utxo/rpc_clients/electrum_rpc/client.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection_manager/manager.rs
  mm2src/coins/utxo/utxo_balance_events.rs
Labels: status: pending review

#2436 chore(release): complete v2.4.0-beta changelogs
  CHANGELOG.md
Labels: status: pending review

#2413 deps(timed-map): bump to `1.3.1`
  Cargo.lock
Labels: status: pending review, improvement: dependencies, 2.5.0-beta

#2316 fix(UTXO): improve tx fee calculation and min relay fee handling
  mm2src/coins/lightning/ln_platform.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/rpc_command/lightning/open_channel.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common_tests.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo/utxo_withdraw.rs
  mm2src/coins/z_coin.rs
Labels: status: pending review, priority: medium, bug: API, 2.5.0-beta

#2425 feat(tron): initial groundwork for full TRON integration
  .github/workflows/test.yml
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/coins_tests.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/eth_wasm_tests.rs
  mm2src/coins/eth/eth_withdraw.rs
  mm2src/coins/eth/for_tests.rs
  mm2src/coins/eth/tron.rs
  mm2src/coins/eth/tron/address.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/hd_wallet/pubkey.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/init_create_account.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/rpcs.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review, 2.5.0-beta, breaking-change: config

#2427 chore(deps): remove base58 dep
  Cargo.lock
  mm2src/adex_cli/Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_coins.rs
  mm2src/mm2_bitcoin/keys/Cargo.toml
  mm2src/mm2_bitcoin/keys/src/legacyaddress.rs
  mm2src/mm2_bitcoin/keys/src/lib.rs
  mm2src/mm2_bitcoin/keys/src/private.rs
Labels: status: pending review, 2.5.0-beta

#2440 fix(eth-balance-events): serialize eth address using AddrToString
  mm2src/coins/eth/eth_balance_events.rs
Labels: status: pending review, priority: high, bug: API

#2455 feat(pubkey-banning): expirable bans
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/pubkey_banning.rs
  mm2src/mm2_p2p/Cargo.toml
Labels: status: pending review, feature: swap, feature: wallet

#2448 chore(build-artifacts): remove duplicated mm2 build artifacts
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  mm2src/mm2_bin_lib/Cargo.toml
Labels: status: pending review

#2398 feat(db-arch): more dbdir to address_dir replacements
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/coin_errors.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lightning/ln_utils.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/siacoin.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage/blockdb/blockdb_sql_storage.rs
  mm2src/coins/z_coin/storage/walletdb/wallet_sql_storage.rs
  mm2src/coins/z_coin/storage/walletdb/wasm/storage.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/coins_activation/Cargo.toml
  mm2src/coins_activation/src/lightning_activation.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_io/src/file_lock.rs
  mm2src/mm2_io/src/fs.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/recreate_swap_data.rs
  mm2src/mm2_main/src/lp_swap/saved_swap.rs
  mm2src/mm2_main/src/lp_swap/swap_lock.rs
  mm2src/mm2_main/src/lp_swap/swap_v2_rpcs.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/tests/docker_tests/z_coin_docker_tests.rs
Labels: status: pending review, priority: urgent, improvement: database, 2.5.0-beta

#2463 chore(docs): add DeepWiki badge to README
  README.md
Labels: status: pending review, improvement: docs

#2445 fix(evm-api): find enabled erc20 token using platform ticker
  mm2src/coins/eth/erc20.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/rpc_command/get_enabled_coins.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
Labels: status: pending review, 2.5.0-beta

#2439 improvement(p2p): remove hardcoded seeds
  README.md
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/tests/docker_tests/docker_ordermatch_tests.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swaps_confs_settings_sync_tests.rs
  mm2src/mm2_main/tests/docker_tests/swaps_file_lock_tests.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_main/tests/mm2_tests/bch_and_slp_tests.rs
  mm2src/mm2_main/tests/mm2_tests/best_orders_tests.rs
  mm2src/mm2_main/tests/mm2_tests/lightning_tests.rs
  mm2src/mm2_main/tests/mm2_tests/lp_bot_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_main/tests/mm2_tests/orderbook_sync_tests.rs
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/lib.rs
  mm2src/mm2_p2p/src/network.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: breaking-change: P2P, status: pending review, priority: urgent, improvement: P2P, 2.5.0-beta

#2408 fix(p2pk): validate expected pubkey correctly for p2pk inputs
  mm2src/coins/qrc20.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/client.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/mm2_bitcoin/keys/src/public.rs
  mm2src/mm2_bitcoin/script/src/script.rs
Labels: status: pending review, priority: urgent, bug: swap, 2.5.0-beta

#2464 improvement(builds): enable static CRT linking for MSVC builds
  .cargo/config.toml
  .github/workflows/dev-build.yml
Labels: status: pending review, 2.5.0-beta

#2474 fix(test): fix HD Wallet message signing tests
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: status: pending review, priority: urgent, 2.5.0-beta
