Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-03, with the labels that each got.

#2371 feat(rpc): add is_success field to legacy MySwapStatusResponse
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/saved_swap.rs
Labels: status: pending review, 2.5.0-beta

#2384 refactor(tx-query): use `TxSearchRequest` for tx queries
  mm2src/coins/tendermint/tendermint_coin.rs
Labels: status: pending review, improvement: protocol

#2390 fix(ci): use correct rustup component syntax in fmt-and-lint job
  .github/workflows/fmt-and-lint.yml
Labels: 2.4.0-beta, status: pending review

#2348 refactor(eth): use trait addr_to_string method instead of old function
  mm2src/coins/coin_balance.rs
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_hd_wallet.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/hd_wallet/address_ops.rs
  mm2src/coins/hd_wallet/coin_ops.rs
  mm2src/coins/hd_wallet/mod.rs
  mm2src/coins/hd_wallet/withdraw_ops.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_structs.rs
  mm2src/coins/nft/nft_tests.rs
  mm2src/coins/nft/storage/sql_storage.rs
  mm2src/coins/nft/storage/wasm/wasm_storage.rs
  mm2src/coins/rpc_command/get_new_address.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/utxo_common/utxo_tx_history_v2_common.rs
  mm2src/coins/utxo/utxo_hd_wallet.rs
  mm2src/coins/utxo/utxo_tx_history_v2.rs
  mm2src/coins_activation/src/erc20_token_activation.rs
  mm2src/coins_activation/src/eth_with_token_activation.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/src/rpc/lp_commands/one_inch/rpcs.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
Labels: status: pending review, 2.5.0-beta

#2377 feat(tendermint): staking queries
  mm2src/coins/lp_coins.rs
  mm2src/coins/rpc_command/tendermint/staking.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review, feature: protocol, 2.5.0-beta

#2391 improvement(dep-stack): replace deprecated `instant` dependency
  Cargo.lock
  mm2src/coins/Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_balance_events.rs
  mm2src/coins/eth/eth_rpc.rs
  mm2src/coins/eth/fee_estimation/eth_fee_events.rs
  mm2src/coins/eth/v2_activation.rs
  mm2src/coins/eth/web3_transport/websocket_transport.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/utxo/rpc_clients/electrum_rpc/connection.rs
  mm2src/common/Cargo.toml
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/data_asker.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/lp_healthcheck.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_ordermatch/order_requests_tracker.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/tests/docker_tests/tendermint_tests.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/behaviours/atomicdex.rs
  mm2src/mm2_p2p/src/behaviours/request_response.rs
Labels: status: pending review, improvement: dependencies

#2385 fix(tx-history): fix unhandled IBC and HTLC events
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/common/log.rs
Labels: status: pending review, status: pending test, improvement: tests, 2.5.0-beta, bug: tests

#2112 feat(swap): add utxo/cosmos/ARRR pre-burn address output
  .github/workflows/dev-build.yml
  .github/workflows/release-build.yml
  mm2src/coins/Cargo.toml
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lightning.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/lp_price.rs
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/qrc20.rs
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/coins/siacoin.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/test_coin.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common/utxo_tx_history_v2_common.rs
  mm2src/coins/utxo/utxo_standard.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/tx_streaming_tests/native.rs
  mm2src/coins/z_coin/z_coin_native_tests.rs
  mm2src/coins/z_coin/z_htlc.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/common/common.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/database/my_swaps.rs
  mm2src/mm2_main/src/ext_api.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/swap_watcher.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_inner.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests/qrc20_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_proto_v2_tests.rs
  mm2src/mm2_main/tests/docker_tests/swap_watcher_tests.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
  mm2src/mm2_main/tests/docker_tests_sia_unique.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
  mm2src/mm2_test_helpers/src/structs.rs
  mm2src/trading_api/Cargo.toml
  mm2src/trading_api/src/one_inch_api/client.rs
Labels: status: pending review, priority: high, 2.5.0-beta

#2378 feat(db-arch): ctx functions and use of global db
  mm2src/coins/Cargo.toml
  mm2src/coins/utxo/utxo_block_header_storage/mod.rs
  mm2src/mm2_core/Cargo.toml
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/Cargo.toml
  mm2src/mm2_main/src/database/stats_nodes.rs
  mm2src/mm2_main/src/lp_native_dex.rs
Labels: status: pending review, improvement: database, 2.5.0-beta

#2323 feat(tpu): implement 0 dexfee for kmd trading pairs
  mm2src/coins/eth.rs
  mm2src/coins/eth/eth_tests.rs
  mm2src/coins/lp_coins.rs
  mm2src/coins/utxo/slp.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_number/src/mm_number.rs
Labels: status: pending review, 2.5.0-beta

#2401 improvement(event-streaming): move UnknownClient error to trace level
  mm2src/rpc_task/src/manager.rs
Labels: status: pending review, improvement: RPC

#2374 feat(ARRR): dockerize zombie/pirate tests
  .gitignore
  mm2src/coins/z_coin.rs
  mm2src/coins/z_coin/storage.rs
  mm2src/coins/z_coin/tx_streaming_tests/native.rs
  mm2src/coins/z_coin/z_coin_errors.rs
  mm2src/coins/z_coin/z_htlc.rs
  mm2src/coins/z_coin/z_rpc.rs
  mm2src/mm2_main/tests/docker_tests/docker_tests_common.rs
  mm2src/mm2_main/tests/docker_tests/mod.rs
  mm2src/mm2_main/tests/docker_tests/z_coin_docker_tests.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review, 2.5.0-beta
