Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-06, with the labels that each got.

#2459 feat(ibc-routing-part-1): supporting entire Cosmos network for swaps
  mm2src/coins/Cargo.toml
  mm2src/coins/lp_coins.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
Labels: status: pending review, priority: urgent, feature: swap

#2450 improvement(RPC): unified interface for legacy and current RPC interfaces
  mm2src/mm2_main/src/rpc.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher_legacy.rs
  mm2src/mm2_main/tests/mm2_tests/lightning_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: status: pending review, priority: high, improvement: RPC

#2481 deps(timed-map): bump to 1.4.1
  Cargo.lock
  Cargo.toml
Labels: status: pending review, improvement: dependencies, bug: CLI

#2441 improvement(event-streaming): strong type streamer IDs
  mm2src/coins/eth/eth_balance_events.rs
  mm2src/coins/eth/fee_estimation/eth_fee_events.rs
  mm2src/coins/tendermint/tendermint_balance_events.rs
  mm2src/coins/utxo/tx_history_events.rs
  mm2src/coins/utxo/utxo_balance_events.rs
  mm2src/coins/z_coin/tx_history_events.rs
  mm2src/coins/z_coin/tx_streaming_tests/native.rs
  mm2src/coins/z_coin/z_balance_streaming.rs
  mm2src/mm2_core/src/data_asker.rs
  mm2src/mm2_event_stream/src/event.rs
  mm2src/mm2_event_stream/src/lib.rs
  mm2src/mm2_event_stream/src/manager.rs
  mm2src/mm2_event_stream/src/streamer.rs
  mm2src/mm2_event_stream/src/streamer_ids.rs
  mm2src/mm2_main/src/heartbeat_event.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/order_events.rs
  mm2src/mm2_main/src/lp_ordermatch/orderbook_events.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/maker_swap_v2.rs
  mm2src/mm2_main/src/lp_swap/swap_events.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/lp_swap/taker_swap_v2.rs
  mm2src/mm2_main/src/rpc/streaming_activations/disable.rs
  mm2src/mm2_main/src/rpc/streaming_activations/mod.rs
  mm2src/mm2_p2p/src/application/network_event.rs
  mm2src/rpc_task/src/manager.rs
Labels: status: pending review, priority: high, improvement: API

#2487 fix(dns): better ip resolution
  mm2src/mm2_net/src/ip_addr.rs
Labels: status: pending review, bug: core

#2485 fix(startup): don't initialize WalletConnect during startup
  mm2src/mm2_main/src/lp_native_dex.rs
Labels: status: pending review, bug: wallet

#2476 feat(ibc-routing-part-2): supporting entire Cosmos network for swaps
  mm2src/coins/tendermint/htlc/mod.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/tendermint/wallet_connect.rs
  mm2src/coins_activation/src/tendermint_token_activation.rs
  mm2src/coins_activation/src/tendermint_with_assets_activation.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/my_orders_storage.rs
  mm2src/mm2_main/src/lp_swap/maker_swap.rs
  mm2src/mm2_main/src/lp_swap/recreate_swap_data.rs
  mm2src/mm2_main/src/lp_swap/taker_swap.rs
  mm2src/mm2_main/src/ordermatch_tests.rs
  mm2src/mm2_main/tests/docker_tests/eth_docker_tests.rs
  mm2src/mm2_test_helpers/src/electrums.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review, feature: swap, improvement: protocol

#2483 improvement(orders): remove BTC specific volume from min_trading_vol logic
  mm2src/coins/utxo/utxo_common.rs
Labels: status: pending review, improvement: orders

#2494 chore(release): add changelog entries for v2.5.0-beta
  CHANGELOG.md
Labels: status: pending review

#2501 chore(release): propagate `delete_wallet` RPC (staging→dev)
  docs/DEV_ENVIRONMENT.md
  mm2src/coins/qrc20/qrc20_tests.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_wallet.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_storage.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_wasm_db.rs
  mm2src/mm2_main/src/rpc/dispatcher/dispatcher.rs
  mm2src/mm2_main/src/wasm_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: status: pending review

#2473 chore(core): replace hash_raw_entry with stable entry() API
  mm2src/coins/lp_coins.rs
  mm2src/coins/utxo/tx_cache/fs_tx_cache.rs
  mm2src/common/common.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/order_requests_tracker.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/tests/docker_tests_main.rs
  mm2src/mm2_main/tests/docker_tests_sia_unique.rs
Labels: status: pending review, 2.6.0-beta

#2504 fix(hw-wallet): avoid calling `get_enabled_address` in trezor-based coin init
  mm2src/coins/coin_balance.rs
  mm2src/coins/hd_wallet/coin_ops.rs
  mm2src/coins/hd_wallet/errors.rs
  mm2src/coins/hd_wallet/mod.rs
  mm2src/coins/utxo/bch.rs
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/utxo_builder/utxo_coin_builder.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_standard.rs
Labels: status: pending review, priority: urgent

#2508 fix(walletconnect): centralize connection and retry logic
  mm2src/kdf_walletconnect/src/connection_handler.rs
  mm2src/kdf_walletconnect/src/lib.rs
Labels: status: pending review, priority: urgent, 2.5.0-beta

#2513 chore(release): propagate walletconnect connection hotfix (staging→dev)
  mm2src/kdf_walletconnect/src/connection_handler.rs
  mm2src/kdf_walletconnect/src/lib.rs
Labels: status: pending review
