Repository KomodoPlatform/komodo-defi-framework, pull requests merged in 2025-04, with the labels that each got.

#2396 feat(spark): support FIRO Spark verbose tx
  mm2src/coins/utxo.rs
  mm2src/coins/utxo/slp.rs
  mm2src/coins/utxo/utxo_common.rs
  mm2src/coins/utxo/utxo_common/utxo_tx_history_v2_common.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/coins/utxo_signer/src/sign_common.rs
  mm2src/mm2_bitcoin/chain/src/for_tests/firo_c50e5a3f16744ac86bacae28d9251a29bf754d250592bce16a953cd961b584d5
  mm2src/mm2_bitcoin/chain/src/transaction.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/script.rs
  mm2src/mm2_bitcoin/rpc/src/v1/types/transaction.rs
  mm2src/mm2_bitcoin/script/src/sign.rs
Labels: status: pending review, 2.5.0-beta

#2318 improvement(best-orders): return an rpc error when we can't find best orders
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_ordermatch.rs
  mm2src/mm2_main/src/lp_ordermatch/best_orders.rs
Labels: status: pending review, improvement: RPC, 2.5.0-beta

#2407 improvement(network): remove static IPs from seed lists
  Cargo.lock
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/lp_network.rs
  mm2src/mm2_main/src/lp_stats.rs
  mm2src/mm2_net/src/ip_addr.rs
  mm2src/mm2_net/src/lib.rs
  mm2src/mm2_p2p/Cargo.toml
  mm2src/mm2_p2p/src/network.rs
Labels: status: pending review, improvement: P2P

#2412 test(electrums): fix failing test_one_unavailable_electrum_proto_version
  mm2src/coins/utxo/utxo_tests.rs
Labels: 2.4.0-beta, status: pending review

#2404 fix(tx-history): token information and query
  mm2src/coins/lp_coins.rs
  mm2src/coins/my_tx_history_v2.rs
  mm2src/coins/tendermint/mod.rs
  mm2src/coins/tendermint/tendermint_coin.rs
  mm2src/coins/tendermint/tendermint_token.rs
  mm2src/coins/tendermint/tendermint_tx_history_v2.rs
  mm2src/coins/tx_history_storage/mod.rs
  mm2src/mm2_test_helpers/dummy_files/iris-ibc-nucleus-history.json
  mm2src/mm2_test_helpers/dummy_files/nucleus-history.json
  mm2src/mm2_test_helpers/src/structs.rs
Labels: 2.4.0-beta, status: pending review, improvement: wallet

#2389 fix(wasm): unify error handling for mm2_main
  mm2src/mm2_bin_lib/src/lib.rs
  mm2src/mm2_bin_lib/src/mm2_native_lib.rs
  mm2src/mm2_bin_lib/src/mm2_wasm_lib.rs
  mm2src/mm2_main/src/lp_native_dex.rs
  mm2src/mm2_main/src/mm2.rs
  mm2src/mm2_main/src/wasm_tests.rs
  mm2src/mm2_main/tests/integration_tests_common/mod.rs
Labels: 2.4.0-beta, status: pending review, breaking-change: bindings

#2386 fix(nft): make `update_nft` work with hd wallets using the enabled address
  mm2src/coins/eth.rs
  mm2src/coins/nft.rs
  mm2src/coins/nft/nft_errors.rs
Labels: 2.4.0-beta, status: in progress, bug: hd-wallet

#2400 fix(wallets): prevent path traversal in `wallet_file_path` and update file extension
  mm2src/mm2_core/src/mm_ctx.rs
  mm2src/mm2_main/src/lp_wallet.rs
  mm2src/mm2_main/src/lp_wallet/mnemonics_storage.rs
  mm2src/mm2_test_helpers/src/for_tests.rs
Labels: 2.4.0-beta, status: pending review, priority: urgent

#2415 chore(release): add changelog entries for v2.4.0-beta
  CHANGELOG.md
Labels: status: pending review

#2416 fix(makerbot): add LiveCoinWatch price provider
  mm2src/coins/lp_price.rs
Labels: 2.4.0-beta, status: pending review, bug: wallet

#2419 chore(RPC): use consistent param name for QTUM delegation
  mm2src/coins/utxo/qtum.rs
  mm2src/coins/utxo/qtum_delegation.rs
  mm2src/coins/utxo/utxo_tests.rs
  mm2src/mm2_main/tests/mm2_tests/mm2_tests_inner.rs
Labels: 2.4.0-beta, status: pending review

#2423 feat(taproot): support parsing taproot output address types
  mm2src/mm2_bitcoin/rpc/src/v1/types/script.rs
  mm2src/mm2_bitcoin/script/src/script.rs
Labels: 2.4.0-beta, status: pending review, priority: medium, bug: wallet

#2424 fix(evm): make `withdraw_nft` work in HD mode
  mm2src/coins/eth.rs
Labels: status: pending review
